"""
McGill Faculty of Arts – Social Sciences: Cognitive Science, Anthropology, Economics, Political Science, Psychology, Sociology
Sub-module of arts_degree_requirements.py
"""

ARTS_SOCIAL_SCIENCES = [
  {
    "program_key": "cognitive_science_minor",
    "name": "Cognitive Science – Minor (B.Sc.)",
    "program_type": "minor",
    "faculty": "Faculty of Arts",
    "total_credits": 24,
    "description": (
      "The Minor in Cognitive Science is intended to allow students in the Faculty of Arts "
      "or the Faculty of Science to explore the interdisciplinary study of cognition. "
      "Open to both faculties. Students complete a minimum of 9 credits each in two areas "
      "from: Computer Science & Mathematics, Linguistics, Philosophy, or Psychology."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/cognitive-science/cognitive-science-minor-bsc/",
    "blocks": [
      {
        "block_key": "cogs_required",
        "title": "Required Course",
        "block_type": "required",
        "credits_needed": 3,
        "courses_needed": None,
        "group_name": None,
        "notes": "Must be taken by all students in the minor.",
        "sort_order": 1,
        "courses": [
          {"subject": "PSYC", "catalog": "433", "title": "Cognitive Science", "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "cogs_comp_sci_math",
        "title": "Computer Science and Mathematics",
        "block_type": "group",
        "credits_needed": None,
        "courses_needed": None,
        "group_name": "Group – Computer Science and Mathematics",
        "notes": "Students complete a minimum of 9 credits each in two of the four areas. Min 6 credits at 400–500 level across all complementary courses. Students may not take courses from their home department(s).",
        "sort_order": 2,
        "courses": [
          {"subject": "COMP", "catalog": "206",  "title": "Introduction to Software Systems",       "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "230",  "title": "Logic and Computability",                "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "250",  "title": "Introduction to Computer Science",       "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "251",  "title": "Algorithms and Data Structures",         "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "302",  "title": "Programming Languages and Paradigms",    "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "330",  "title": "Theory of Computation",                  "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "527",  "title": "Logic and Computation",                  "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "240",  "title": "Discrete Structures",                    "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "318",  "title": "Mathematical Logic",                     "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogs_linguistics",
        "title": "Linguistics",
        "block_type": "group",
        "credits_needed": None,
        "courses_needed": None,
        "group_name": "Group – Linguistics",
        "notes": "Any LING course at the 300, 400, or 500 level also counts. Students complete a minimum of 9 credits each in two of the four areas.",
        "sort_order": 3,
        "courses": [
          {"subject": "LING", "catalog": "201",  "title": "Introduction to Linguistics",    "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "210",  "title": "Introduction to Speech Science", "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "260",  "title": "Meaning in Language",            "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogs_philosophy",
        "title": "Philosophy",
        "block_type": "group",
        "credits_needed": None,
        "courses_needed": None,
        "group_name": "Group – Philosophy",
        "notes": "Students complete a minimum of 9 credits each in two of the four areas.",
        "sort_order": 4,
        "courses": [
          {"subject": "PHIL", "catalog": "210",  "title": "Introduction to Deductive Logic 1",              "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "221",  "title": "Introduction to History and Philosophy of Science 2", "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "306",  "title": "Philosophy of Mind",                             "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "310",  "title": "Intermediate Logic",                             "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "311",  "title": "Philosophy of Mathematics",                      "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "341",  "title": "Philosophy of Science 1",                        "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "411",  "title": "Topics in Philosophy of Logic and Mathematics",  "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "415",  "title": "Philosophy of Language",                         "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "441",  "title": "Philosophy of Science 2",                        "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "474",  "title": "Phenomenology",                                  "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogs_psychology",
        "title": "Psychology",
        "block_type": "group",
        "credits_needed": None,
        "courses_needed": None,
        "group_name": "Group – Psychology",
        "notes": "Students complete a minimum of 9 credits each in two of the four areas.",
        "sort_order": 5,
        "courses": [
          {"subject": "PSYC", "catalog": "212",  "title": "Perception",                                "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "213",  "title": "Cognition",                                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "301",  "title": "Animal Learning and Theory",                "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "304",  "title": "Child Development",                         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "310",  "title": "Intelligence",                              "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "311",  "title": "Human Cognition and the Brain",             "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "315",  "title": "Computational Psychology",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "319",  "title": "Computational Models - Cognition",          "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "340",  "title": "Psychology of Language",                    "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "410",  "title": "Special Topics in Neuropsychology",         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "413",  "title": "Cognitive Development",                     "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "538",  "title": "Categorization, Communication and Consciousness", "credits": 3, "is_required": False},
        ],
      },
    ],
  },


  # ──────────────────────────────────────────────────────────────────
  # ANTHROPOLOGY
  # ──────────────────────────────────────────────────────────────────
  {
    "program_key": "anthropology_major",
    "name": "Anthropology – Major Concentration",
    "program_type": "major",
    "total_credits": 36,
    "description": (
      "Emphasises the similarity and diversity of human behaviour; "
      "understanding of social and cultural systems; and the processes "
      "of socio-cultural change from human origins to the present."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/anthropology/anthropology-major-concentration-ba/",
    "blocks": [
      {
        "block_key": "intro_200",
        "title": "200-Level Introductory Courses",
        "credits_needed": 6,
        "notes": "6 credits selected from 200-level ANTH courses.",
        "courses": [
          {"subject":"ANTH","catalog":"201","title":"Introduction to Archaeology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Best intro to prehistoric archaeology sub-field"},
          {"subject":"ANTH","catalog":"202","title":"Socio-Cultural Anthropology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Core intro to socio-cultural sub-field — take in U1"},
          {"subject":"ANTH","catalog":"203","title":"Human Evolution","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Biological anthropology foundations"},
          {"subject":"ANTH","catalog":"204","title":"Anthropology of Meaning","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"206","title":"Environment and Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"207","title":"Ethnography Through Film","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Accessible and engaging — great for non-specialists"},
          {"subject":"ANTH","catalog":"209","title":"Anthropology of Religion","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"210","title":"Archaeology of Early Cities","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"212","title":"Anthropology of Development","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"213","title":"Archaeology of Health and Disease","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"214","title":"Violence, Warfare, Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"222","title":"Legal Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"227","title":"Medical Anthropology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Very popular; bridges medicine and culture"},
        ],
      },
      {
        "block_key": "core_350",
        "title": "350-Level Core (Theory & Methods)",
        "credits_needed": 6,
        "notes": "6 credits from 350-level core courses. U2 standing required. ANTH 352 is required for Honours; strongly recommended for Major.",
        "courses": [
          {"subject":"ANTH","catalog":"352","title":"History of Anthropological Theory","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Essential theoretical grounding; required for Honours"},
          {"subject":"ANTH","catalog":"355","title":"Theories of Culture and Society","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Pairs well with ANTH 352"},
          {"subject":"ANTH","catalog":"357","title":"Archaeological Methods","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"358","title":"The Process of Anthropological Research","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Research methods — essential for Honours"},
          {"subject":"ANTH","catalog":"359","title":"History of Archaeological Theory","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "upper_300_400",
        "title": "Additional ANTH Electives",
        "credits_needed": 24,
        "min_credits_400": 6,
        "max_credits_200": 6,
        "notes": "24 additional ANTH credits; at least 6 credits from two 400-level ANTH courses; at most 6 credits at the 200-level. Max one 3-credit Special Topics course at 300-level and one at 400-level.",
        "courses": [
          {"subject":"ANTH","catalog":"302","title":"New Horizons in Medical Anthropology","credits":3,"is_required":False,"recommended":True},
          {"subject":"ANTH","catalog":"303","title":"Ethnographies of Post-socialism","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"304","title":"Chinese Culture in Ethnography and Film","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"307","title":"Andean Prehistory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"308","title":"Political Anthropology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Covers power, state, resistance — highly engaging"},
          {"subject":"ANTH","catalog":"312","title":"Zooarchaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"314","title":"Psychological Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"315","title":"Society/Culture: East Africa","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"318","title":"Globalization and Religion","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"338","title":"Indigenous Studies of Anthropology","credits":3,"is_required":False,"recommended":True},
          {"subject":"ANTH","catalog":"437","title":"Historical Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"438","title":"Topics in Medical Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"440","title":"Cognitive Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"450","title":"Archaeology of Landscape","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"451","title":"Research in Society and Development in Africa","credits":3,"is_required":False},
          # ── 500-level open to U3 students ──
          {"subject":"ANTH","catalog":"501","title":"Anthropology Beyond the Human","credits":3,"is_required":False,"recommendation_reason":"U3 only; cutting-edge theoretical perspectives"},
          {"subject":"ANTH","catalog":"502","title":"Social Life of Death","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"504","title":"Environmental Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"512","title":"Political Ecology","credits":3,"is_required":False,"recommended":True},
        ],
      },
    ],
  },

  {
    "program_key": "anthropology_minor",
    "name": "Anthropology – Minor Concentration",
    "program_type": "minor",
    "faculty": "Faculty of Arts",
    "total_credits": 18,
    "description": "18 credits in Anthropology. May focus on one sub-field or explore all. Can be expanded into the Major.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/anthropology/anthropology-minor-concentration-ba/",
    "blocks": [
      {
        "block_key": "anth_minor_200",
        "title": "200-Level ANTH Courses",
        "credits_needed": 6,
        "notes": "6–9 credits from 200-level ANTH courses.",
        "courses": [
          {"subject":"ANTH","catalog":"201","title":"Introduction to Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"202","title":"Socio-Cultural Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"203","title":"Human Evolution","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"204","title":"Anthropology of Meaning","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"206","title":"Environment and Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"207","title":"Ethnography Through Film","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"209","title":"Anthropology of Religion","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"210","title":"Archaeology of Early Cities","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"212","title":"Anthropology of Development","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"213","title":"Archaeology of Health and Disease","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"214","title":"Violence, Warfare, Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"222","title":"Legal Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"227","title":"Medical Anthropology","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "anth_minor_300up",
        "title": "300/400/500-Level ANTH Courses",
        "credits_needed": 9,
        "notes": "9–12 credits from ANTH 300-, 400-, or 500-level. Max 3 credits at 400/500-level. Max 1 Special Topics course.",
        "courses": [
          {"subject":"ANTH","catalog":"302","title":"New Horizons in Medical Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"303","title":"Ethnographies of Post-socialism","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"304","title":"Chinese Culture in Ethnography and Film","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"307","title":"Andean Prehistory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"308","title":"Political Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"312","title":"Zooarchaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"313","title":"Bioarchaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"314","title":"Psychological Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"315","title":"Society/Culture: East Africa","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"318","title":"Globalization and Religion","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"319","title":"Inka Archaeology and Ethnohistory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"322","title":"Social Change in Modern Africa","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"325","title":"Anthropology of the Self","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"326","title":"Anthropology of Latin America","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"327","title":"Anthropology of South Asia","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"330","title":"Traditional Whaling Societies","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"331","title":"Prehistory of East Asia","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"332","title":"Mesoamerican Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"338","title":"Indigenous Studies of Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"339","title":"Ecological Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"340","title":"Middle Eastern Society and Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"343","title":"Anthropology and the Animal","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"344","title":"Quantitative Approaches to Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"352","title":"History of Anthropological Theory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"355","title":"Theories of Culture and Society","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"357","title":"Archaeological Methods","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"358","title":"The Process of Anthropological Research","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"359","title":"History of Archaeological Theory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"361","title":"Archaeology of South Asia","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"365","title":"Anthropology of Forced Migration and Displacement","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"370","title":"Anthropology and the Image","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"380","title":"Special Topic 1","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"381","title":"Special Topic 2","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"385","title":"Sex, Science and Culture","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"402","title":"Topics in Ethnography","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"403","title":"Current Issues in Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"407","title":"Anthropology of the Body","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"408","title":"Sensory Ethnography","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"410","title":"Great Debates in Anthropological Theory","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"415","title":"Anthropology of Religious Experience","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"416","title":"Environment/Development: Africa","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"418","title":"Environment and Development","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"419","title":"Archaeology of Hunter-Gatherers","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"420","title":"Anthropology of Economic Relations","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"423","title":"Mind, Brain and Psychopathology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"432","title":"The Aztecs","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"436","title":"North American Native Peoples","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"437","title":"Historical Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"438","title":"Topics in Medical Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"440","title":"Cognitive Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"450","title":"Archaeology of Landscape","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"499","title":"Internship: Anthropology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"500","title":"Chinese Diversity and Diaspora","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"501","title":"Anthropology Beyond the Human","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"502","title":"Social Life of Death","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"503","title":"Production of the Past","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"504","title":"Environmental Archaeology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"510","title":"Advanced Problems in Anthropology of Religion","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"512","title":"Political Ecology","credits":3,"is_required":False},
          {"subject":"ANTH","catalog":"520","title":"Problems and Perspectives in Medical Anthropology","credits":3,"is_required":False},
        ],
      },
    ],
  },

  # ──────────────────────────────────────────────────────────────────
  # ECONOMICS
  # ──────────────────────────────────────────────────────────────────
  {
    "program_key": "economics_major",
    "name": "Economics – Major Concentration",
    "program_type": "major",
    "total_credits": 36,
    "description": (
      "A planned sequence of courses designed to permit the student a degree "
      "of specialization in economics. Students entering U1 proceed directly "
      "to ECON 230D1/D2 (not ECON 208/209)."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/economics/economics-major-concentration-ba/",
    "blocks": [
      {
        # ── 200-LEVEL GATEWAY ──────────────────────────────────────────────────
        # Note: Major students are advised to skip ECON 208/209 and go directly to
        # ECON 230D1/D2. However, these 200-level courses are counted in the
        # complementary credits (above 209, max 6 credits) and are listed here so
        # students can see the full ECON 200-level offering.
        "block_key": "intro_200",
        "title": "200-Level Economics Courses",
        "credits_needed": None,
        "notes": (
          "Major students: proceed directly to ECON 230D1/D2 — do NOT take ECON 208/209 first. "
          "These 200-level courses are eligible as complementary electives (max 6cr at 200-level, "
          "all numbered above 209). ECON 208, 209, 295, and 399 are ineligible for the major. "
          "In general, 200-level courses have NO prerequisites. "
          "300/400-level courses require ECON 230D1/D2 (or ECON 208+209 as prereq equivalent). "
          "400-level also requires Calculus 1 or equivalent."
        ),
        "courses": [
          {
            "subject":"ECON","catalog":"208",
            "title":"Microeconomic Analysis and Applications",
            "credits":3,"is_required":False,
            "recommendation_reason":"For minor students only — major students should take ECON 230D1/D2 instead",
            "prerequisites":[],
            "restrictions":["Not open to students taking/having taken MGCR 293, ECON 230, or ECON 250"],
          },
          {
            "subject":"ECON","catalog":"209",
            "title":"Macroeconomic Analysis and Applications",
            "credits":3,"is_required":False,
            "recommendation_reason":"Minor entry point — macro complement to ECON 208",
            "prerequisites":["ECON 208 or permission of instructor"],
            "restrictions":["Not open to students who have taken ECON 330D1/D2"],
          },
          {
            "subject":"ECON","catalog":"219",
            "title":"Current Economic Problems: Topics",
            "credits":3,"is_required":False,"recommended":True,
            "recommendation_reason":"Topical Canadian economic issues — accessible to all students; no prerequisites",
            "prerequisites":[],
            "terms":["Winter"],
          },
          {
            "subject":"ECON","catalog":"221",
            "title":"Economic History",
            "credits":3,"is_required":False,"recommended":True,
            "recommendation_reason":"Survey of economic development and institutions from a historical lens",
            "prerequisites":["ECON 208 + ECON 209 (coreq), or ECON 230D1/D2, or ECON 250D1/D2"],
            "restrictions":["Not open to students who have taken ECON 201 or ECON 221D1/D2"],
          },
          {
            "subject":"ECON","catalog":"223",
            "title":"Political Economy of Trade Policy",
            "credits":3,"is_required":False,"recommended":True,
            "recommendation_reason":"Trade theory + political economy; no calculus required; accessible 200-level option",
            "prerequisites":[],
          },
          {
            "subject":"ECON","catalog":"225",
            "title":"Economics of the Environment",
            "credits":3,"is_required":False,"recommended":True,
            "recommendation_reason":"Environmental policy, pollution economics, green fiscal instruments — no prereqs",
            "prerequisites":[],
          },
          {
            "subject":"ECON","catalog":"227D1",
            "title":"Economic Statistics 1",
            "credits":3,"is_required":True,"recommended":True,
            "recommendation_reason":"REQUIRED for major — take Fall U1. Distributions, testing, regression, index numbers",
            "prerequisites":[],
            "notes":"Must register for both 227D1 (Fall) and 227D2 (Winter) consecutively",
          },
          {
            "subject":"ECON","catalog":"227D2",
            "title":"Economic Statistics 2",
            "credits":3,"is_required":True,
            "recommendation_reason":"Continuation of ECON 227D1 — take Winter U1 immediately after 227D1",
            "prerequisites":["ECON 227D1"],
          },
          {
            "subject":"ECON","catalog":"230D1",
            "title":"Microeconomic Theory 1",
            "credits":3,"is_required":True,"recommended":True,
            "recommendation_reason":"REQUIRED — core micro entry for all 300+ courses. Take Fall U1 simultaneously with ECON 227D1",
            "prerequisites":[],
            "notes":"Must register for both 230D1 (Fall) and 230D2 (Winter) consecutively. Do NOT take in U0.",
          },
          {
            "subject":"ECON","catalog":"230D2",
            "title":"Microeconomic Theory 2",
            "credits":3,"is_required":True,
            "prerequisites":["ECON 230D1"],
          },
          {
            "subject":"ECON","catalog":"250D1",
            "title":"Introduction to Economic Theory: Honours 1",
            "credits":3,"is_required":False,"recommended":False,
            "recommendation_reason":"For Honours-track students only. Replaces ECON 230D1/D2 in the Honours program",
            "prerequisites":[],
            "notes":"Do NOT take in U0. Register for 250D1+250D2 consecutively. Placement exam may be required.",
          },
          {
            "subject":"ECON","catalog":"250D2",
            "title":"Introduction to Economic Theory: Honours 2",
            "credits":3,"is_required":False,
            "prerequisites":["ECON 250D1"],
          },
          {
            "subject":"ECON","catalog":"257D1",
            "title":"Economic Statistics – Honours 1",
            "credits":3,"is_required":False,
            "recommendation_reason":"Honours track stats — replaces ECON 227D1/D2 for Honours students",
            "prerequisites":[],
            "notes":"For Honours program students — must register for 257D1 + 257D2 consecutively",
          },
          {
            "subject":"ECON","catalog":"257D2",
            "title":"Economic Statistics – Honours 2",
            "credits":3,"is_required":False,
            "prerequisites":["ECON 257D1"],
          },
        ],
      },
      {
        "block_key": "required_core",
        "title": "Required Core (18 credits)",
        "credits_needed": 18,
        "notes": (
          "All six courses required. ECON 230D1/D2 and ECON 227D1/D2 are listed above in the "
          "200-level block since they are 200-level courses. ECON 332/333 require ECON 230D2 as prereq."
        ),
        "courses": [
          {"subject":"ECON","catalog":"227D1","title":"Economic Statistics 1","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Take Fall U1 — stats foundation for all upper courses. No prerequisites."},
          {"subject":"ECON","catalog":"227D2","title":"Economic Statistics 2","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Continuation; must take with 227D1 in consecutive terms"},
          {"subject":"ECON","catalog":"230D1","title":"Microeconomic Theory 1","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Core micro; entry point for all 300+ courses. No prerequisites (do not take in U0)."},
          {"subject":"ECON","catalog":"230D2","title":"Microeconomic Theory 2","credits":3,"is_required":True},
          {"subject":"ECON","catalog":"332","title":"Macroeconomic Theory: Majors 1","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Take after 230D2; macro side of the core. Prereq: ECON 230D1/D2."},
          {"subject":"ECON","catalog":"333","title":"Macroeconomic Theory: Majors 2","credits":3,"is_required":True},
        ],
      },
      {
        "block_key": "complementary",
        "title": "Complementary Economics Electives (18 credits)",
        "credits_needed": 18,
        "min_credits_400": 6,
        "max_credits_200": 6,
        "notes": "18 credits from ECON courses numbered above 209. At least 6 credits must be at the 400- or 500-level. Max 6 credits at the 200-level. ECON 295 and 399 are ineligible.",
        "courses": [
          # ── 300-level electives (confirmed from mcgill.ca/economics/undergraduate/courses/300-level) ──
          {"subject":"ECON","catalog":"302","title":"Money, Banking and Government Policy","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Covers central banking, monetary policy, quantitative easing — great for finance/policy track"},
          {"subject":"ECON","catalog":"304","title":"Financial Instruments and Institutions","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Bonds, equities, financial innovation — pairs well with ECON 302"},
          {"subject":"ECON","catalog":"305","title":"Industrial Organization","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Mergers, market structure, R&D — strong applied micro elective"},
          {"subject":"ECON","catalog":"306","title":"Labour Markets and Wages","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Labour supply/demand, unions, wage policy — popular policy elective"},
          {"subject":"ECON","catalog":"308","title":"Governmental Policy Towards Business","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Competition policy, regulation, privatization in Canadian context"},
          {"subject":"ECON","catalog":"310","title":"Introduction to Behavioural Economics","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Bounded rationality, nudge theory, behavioural game theory — highly accessible"},
          {"subject":"ECON","catalog":"313","title":"Economic Development 1","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Micro development — poverty, inequality, firms in developing countries"},
          {"subject":"ECON","catalog":"314","title":"Economic Development 2","credits":3,"is_required":False,"recommendation_reason":"Macro development — growth theory, debt crises, structural adjustment. Prereq: ECON 313"},
          {"subject":"ECON","catalog":"316","title":"The Underground Economy","credits":3,"is_required":False,"recommendation_reason":"Black markets, contraband trade, money laundering — unique perspective on markets"},
          {"subject":"ECON","catalog":"319","title":"Economic Crises","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Causes & consequences of financial crises — directly relevant to post-2008 economy"},
          {"subject":"ECON","catalog":"326","title":"Ecological Economics","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Economic growth vs. environment, green fiscal policy, fossil fuels — strong elective"},
          {"subject":"ECON","catalog":"337","title":"Introductory Econometrics 1","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Quantitative methods for statistical investigations — essential for research track"},
          {"subject":"ECON","catalog":"338","title":"Introductory Econometrics 2","credits":3,"is_required":False,"recommendation_reason":"Simultaneous equations, time series, forecasting. Prereq: ECON 337"},
          # ── 400-level electives (confirmed from mcgill.ca/economics/undergraduate/courses/400-level) ──
          {"subject":"ECON","catalog":"405","title":"Natural Resource Economics","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Non-renewable/renewable resources, rent & taxation — satisfies 400-level requirement"},
          {"subject":"ECON","catalog":"406","title":"Topics in Economic Policy","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Selected policy issues; topic varies — check outline for current year"},
          {"subject":"ECON","catalog":"408","title":"Public Sector Economics 1","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Public goods, government spending — key for policy/public sector careers"},
          {"subject":"ECON","catalog":"409","title":"Public Sector Economics 2","credits":3,"is_required":False,"recommendation_reason":"Taxation theory & Canadian institutions. Prereq: ECON 408"},
          {"subject":"ECON","catalog":"416","title":"Topics in Economic Development 2","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Micro-level analysis of developing economies — strong applied development course"},
          {"subject":"ECON","catalog":"420","title":"Topics in Economic Theory","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Advanced welfare economics, general equilibrium, game theory — great for grad school prep"},
          {"subject":"ECON","catalog":"423","title":"International Trade","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Classical and modern trade theory, WTO, tariffs — popular 400-level option"},
          {"subject":"ECON","catalog":"424","title":"International Payments","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Balance of payments, exchange rates, global capital markets — pairs with ECON 423"},
          {"subject":"ECON","catalog":"426","title":"Labour Economics","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Rigorous empirical labour economics — minimum wage, UI, training subsidies"},
          {"subject":"ECON","catalog":"430","title":"The Economics of Well-Being","credits":3,"is_required":False,"recommendation_reason":"Subjective well-being, happiness economics — unique interdisciplinary perspective"},
          {"subject":"ECON","catalog":"434","title":"Current Economic Problems","credits":3,"is_required":False,"recommendation_reason":"Contemporary economic issues; topic varies annually — always relevant"},
          {"subject":"ECON","catalog":"437","title":"Methods for Causal Inference","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"RCTs, IV, DiD, RDD — essential for empirical research careers. Prereq: ECON 337+338"},
          {"subject":"ECON","catalog":"440","title":"Health Economics","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Canada's health care system from an economist's view — very accessible 400-level"},
          {"subject":"ECON","catalog":"447","title":"Economics of Information and Uncertainty","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Asymmetric information, principal-agent, moral hazard — strong theory elective"},
          # ── 500-level (open to advanced undergrads) ──
          {"subject":"ECON","catalog":"510","title":"Experimental Economics","credits":3,"is_required":False,"recommendation_reason":"Lab and field experiments in economics — only for advanced students"},
          {"subject":"ECON","catalog":"546","title":"Game Theory","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Strategic interaction, Nash equilibrium, mechanism design — highly sought after"},
        ],
      },
    ],
  },

  {
    "program_key": "economics_minor",
    "name": "Economics – Minor Concentration",
    "program_type": "minor",
    "total_credits": 18,
    "description": "Provides a moderate level of specialization in Economics. ECON 208 and 209 count only toward the minor, not the major.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/economics/economics-minor-concentration-ba/",
    "blocks": [
      {
        "block_key": "intro",
        "title": "Introductory Courses (6 credits)",
        "credits_needed": 6,
        "notes": "ECON 208 and 209 are allowed for the minor (unlike the major).",
        "courses": [
          {"subject":"ECON","catalog":"208","title":"Microeconomic Analysis and Applications","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Standard entry for minor students"},
          {"subject":"ECON","catalog":"209","title":"Macroeconomic Analysis and Applications","credits":3,"is_required":False,"recommended":True},
        ],
      },
      {
        "block_key": "upper",
        "title": "Upper-Level ECON Courses (12 credits)",
        "credits_needed": 12,
        "min_level": 200,
        "notes": "12 credits of ECON courses above 209, at least 6 credits at 300-level or above. Max 6 credits at 200-level.",
        "courses": [
          {"subject":"ECON","catalog":"227D1","title":"Economic Statistics 1","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"227D2","title":"Economic Statistics 2","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"219","title":"Current Economic Problems","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"221","title":"Economic History","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"223","title":"Political Economy of Trade Policy","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"225","title":"Economics of the Environment","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"302","title":"Money, Banking and Government Policy","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"305","title":"Industrial Organization","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"306","title":"Labour Markets and Wages","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"308","title":"Governmental Policy Towards Business","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"310","title":"Introduction to Behavioural Economics","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"313","title":"Economic Development 1","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"319","title":"Economic Crises","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"326","title":"Ecological Economics","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"337","title":"Introductory Econometrics 1","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"408","title":"Public Sector Economics 1","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"423","title":"International Trade","credits":3,"is_required":False,"recommended":True},
          {"subject":"ECON","catalog":"437","title":"Methods for Causal Inference","credits":3,"is_required":False},
          {"subject":"ECON","catalog":"440","title":"Health Economics","credits":3,"is_required":False},
        ],
      },
    ],
  },

  # ──────────────────────────────────────────────────────────────────
  # POLITICAL SCIENCE
  # ──────────────────────────────────────────────────────────────────
  {
    "program_key": "political_science_major",
    "name": "Political Science – Major Concentration",
    "program_type": "major",
    "total_credits": 36,
    "description": (
      "A 36-credit program covering four fields: Comparative Politics, "
      "International Relations, Canadian Politics, and Political Theory. "
      "Methods courses (POLI 210/311/312/313) may count toward any field. "
      "Max 18 credits in any single field (21 for Comparative Politics). "
      "At least one 200-level course in a field before taking 300/400-level courses in that field."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/political-science/political-science-major-concentration-ba/",
    "blocks": [
      {
        "block_key": "methods",
        "title": "Methods / Research",
        "credits_needed": None,
        "notes": "Methods courses; may count toward any field's credit cap.",
        "courses": [
          {"subject":"POLI","catalog":"210","title":"Political Science Research Methods","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Core methods course; no prerequisites"},
          {"subject":"POLI","catalog":"311","title":"Introduction to Quantitative Political Science","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"312","title":"Intermediate Quantitative Political Science","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"313","title":"Introduction to Qualitative Methods in Political Science","credits":3,"is_required":False,"recommended":True},
        ],
      },
      {
        "block_key": "canadian_politics",
        "title": "Canadian Politics",
        "credits_needed": None,
        "notes": "Field cap: max 18 credits in Canadian Politics. Must take a 200-level (POLI 221 or 222) before any 300/400-level in this field.",
        "courses": [
          {"subject":"POLI","catalog":"221","title":"Government of Canada","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Best 200-level entry for Canadian Politics field"},
          {"subject":"POLI","catalog":"222","title":"Political Process and Behaviour in Canada","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"317","title":"The Politics of Race in Canada","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"318","title":"Comparative Local Government","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"320","title":"Issues in Canadian Democracy","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"321","title":"Issues: Canadian Public Policy","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"336","title":"Le Québec et le Canada","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"342","title":"Canadian Foreign Policy","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"348","title":"Gender and Canadian Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"371","title":"Challenge of Canadian Federalism","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"372","title":"Indigenous Peoples and the Canadian State","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"379","title":"Topics in Canadian Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"410","title":"Canadian Political Parties","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"412","title":"Canadian Voting/Public Opinion","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"417","title":"Health Care in Canada","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"426","title":"Partis politiques et comportements électoraux au Québec","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"427","title":"Selected Topics: Canadian Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"436","title":"Aboriginal Rights in the Canadian Constitution","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"521","title":"Seminar: Canadian Politics and Government","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "comparative_politics",
        "title": "Comparative Politics",
        "credits_needed": None,
        "notes": "Field cap: max 21 credits in Comparative Politics. Must take a 200-level (POLI 212 or 227) before any 300/400-level in this field.",
        "courses": [
          {"subject":"POLI","catalog":"212","title":"Introduction to Comparative Politics – Europe/North America","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Entry point for Comparative Politics — Europe/North America focus"},
          {"subject":"POLI","catalog":"227","title":"Introduction to Comparative Politics – Global South","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Entry point — Global South focus; also useful for IR/IDS students"},
          {"subject":"POLI","catalog":"316","title":"Black Lives Matter and American Democracy","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"319","title":"Politics of Latin America","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"322","title":"Political Change in South Asia","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"324","title":"Comparative Politics of Africa","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"325","title":"U.S. Politics","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"328","title":"Comparing European Democracies","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"329","title":"Russian Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"330","title":"Law and Courts in Europe","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"331","title":"Politics in East Central Europe","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"338","title":"Topics in Comparative Politics 1","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"339","title":"Topics in Comparative Politics 2","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"340","title":"Comparative Politics of the Middle East","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"357","title":"Politics: Contemporary Europe","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"361","title":"Political Participation in Comparative Perspective","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"369","title":"Politics of Southeast Asia","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"380","title":"Contemporary Chinese Politics","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"381","title":"Politics in Japan and South Korea","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"420","title":"Memory, Place, and Power","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"421","title":"The Politics of Misinformation","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"422","title":"Advanced Topics in Comparative Politics 1","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"423","title":"Politics of Ethno-Nationalism","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"424","title":"Media and Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"431","title":"Nations and Nationalism","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"432","title":"Advanced Topics in Comparative Politics 2","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"435","title":"Identity and Inequality","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"451","title":"The European Union","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"452","title":"Conflict Simulation","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"522","title":"Seminar: Comparative Politics 1","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"524","title":"Seminar: Comparative Politics 2","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "international_relations",
        "title": "International Relations",
        "credits_needed": None,
        "notes": "Field cap: max 18 credits in International Relations. Must take a 200-level (POLI 243 or 244) before any 300/400-level in this field.",
        "courses": [
          {"subject":"POLI","catalog":"243","title":"International Politics of Economic Relations","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"200-level IR entry — IPE focus"},
          {"subject":"POLI","catalog":"244","title":"International Politics: State Behaviour","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"200-level IR entry — security/state behaviour focus"},
          {"subject":"POLI","catalog":"341","title":"Foreign Policy: The Middle East","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"345","title":"International Organizations","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"346","title":"American Foreign Policy","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"347","title":"Arab-Israel Conflict, Crisis, Peace","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"349","title":"Foreign Policy: Asia","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"350","title":"Global Environmental Politics","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"351","title":"The Causes of Major Wars","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"352","title":"International Policy/Foreign Policy: Africa","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"353","title":"Politics of the International Refugee Regime","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"354","title":"Approaches to International Political Economy","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"355","title":"The Politics of International Law","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"358","title":"Political Economy of International Organizations","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"359","title":"Topics in International Politics 1","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"360","title":"Security: War and Peace","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"441","title":"International Political Economy: Trade","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"442","title":"International Relations of Ethnic Conflict","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"443","title":"Intervention in World Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"444","title":"Topics in International Politics 2","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"445","title":"International Political Economy: Monetary Relations","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"446","title":"International Law and Politics of Human Rights","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"448","title":"Gender and International Relations","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"449","title":"Diplomacy in Practice","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"450","title":"Peacebuilding","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"458","title":"(De-) Coloniality","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"575","title":"Seminar: International Politics","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "political_theory",
        "title": "Political Theory",
        "credits_needed": None,
        "notes": "Field cap: max 18 credits in Political Theory. Must take POLI 231 before any 300/400-level in this field.",
        "courses": [
          {"subject":"POLI","catalog":"231","title":"Introduction to Political Theory","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Required 200-level entry for Political Theory field"},
          {"subject":"POLI","catalog":"333","title":"Western Political Theory 1","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"334","title":"Western Political Theory 2","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"362","title":"Political Theory and International Relations","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"363","title":"Contemporary Political Theory","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"364","title":"Radical Political Thought","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"365","title":"Democratic Theory","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"366","title":"Topics in Political Theory 1","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"367","title":"Liberal Political Theory","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"368","title":"Political Theory and Indigeneity","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"433","title":"History of Political/Social Theory 3","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"434","title":"History of Political/Social Theory 4","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"459","title":"Topics in Political Theory 2","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"470","title":"Philosophy, Economy and Society","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"473","title":"Democracy and the Market","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"476","title":"Religion and Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"561","title":"Seminar: Political Theory","credits":3,"is_required":False},
        ],
      },
    ],
  },

  {
    "program_key": "political_science_minor",
    "name": "Political Science – Minor Concentration",
    "program_type": "minor",
    "total_credits": 18,
    "description": "An 18-credit program in four fields: Comparative Politics, International Relations, Canadian Politics, and Political Theory.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/political-science/political-science-minor-concentration-ba/",
    "blocks": [
      {
        "block_key": "all_fields",
        "title": "POLI Courses Across Fields",
        "credits_needed": 18,
        "notes": "6-9 credits at 200-level across at least two different fields. Max 6 credits in any one field.",
        "courses": [
          {"subject":"POLI","catalog":"212","title":"Introduction to Comparative Politics – Europe/North America","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"226","title":"La vie politique québécoise","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"227","title":"Introduction to Comparative Politics – Global South","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"231","title":"Introduction to Political Theory","credits":3,"is_required":False,"recommended":True},
          {"subject":"POLI","catalog":"221","title":"Quebec Politics","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"243","title":"International Politics of Economic Relations","credits":3,"is_required":False},
          {"subject":"POLI","catalog":"244","title":"International Politics: State Behaviour","credits":3,"is_required":False},
          {"subject":"POLI","catalog":None,"title":"Upper-level POLI course","credits":3,"is_required":False},
        ],
      },
    ],
  },

  # ──────────────────────────────────────────────────────────────────
  # PSYCHOLOGY
  # ──────────────────────────────────────────────────────────────────
  {
    "program_key": "psychology_major",
    "name": "Psychology – Major Concentration",
    "program_type": "major",
    "total_credits": 36,
    "description": (
      "Provides a basic overview of psychological science covering core areas "
      "and advanced specialized content. Note: PSYC 204 exemption possible for "
      "CEGEP students with statistics background."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/psychology/psychology-major-concentration-ba/",
    "blocks": [
      {
        "block_key": "required_core",
        "title": "Required Core Courses",
        "block_type": "required",
        "credits_needed": 18,
        "notes": (
          "All six courses are required. PSYC 100 should be completed before entry "
          "(or equivalent CEGEP psychology). PSYC 204 exemption possible for students "
          "with CEGEP statistics background. "
          "Program does not provide sufficient preparation for graduate psychology "
          "or Quebec licensing without additional coursework."
        ),
        "courses": [
          {"subject":"PSYC","catalog":"204","title":"Introduction to Psychological Statistics","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Stats core; take early — required for all 300+ courses"},
          {"subject":"PSYC","catalog":"211","title":"Introductory Behavioural Neuroscience","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Neuro foundation"},
          {"subject":"PSYC","catalog":"212","title":"Perception","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Required U1 core"},
          {"subject":"PSYC","catalog":"213","title":"Cognition","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Required U1 core"},
          {"subject":"PSYC","catalog":"215","title":"Social Psychology","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Required U1 core; most popular PSYC course"},
          {"subject":"PSYC","catalog":"305","title":"Statistics for Experimental Design","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Required U1/U2 stats core"},
        ],
      },
      {
        "block_key": "list_a",
        "title": "List A – Behavioural Neuroscience, Cognition & Quantitative",
        "credits_needed": 3,
        "notes": "3 credits from List A.",
        "courses": [
          {"subject":"PSYC","catalog":"212","title":"Perception","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Fascinating; good entry to cognitive track"},
          {"subject":"PSYC","catalog":"213","title":"Introduction to Cognitive Science","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"211","title":"Introductory Behavioural Neuroscience","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Neuro foundation for List A"},
          {"subject":"PSYC","catalog":"304","title":"Animal Learning and Theory","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"306","title":"Research Methods in Psychology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Methods; required for Honours"},
          {"subject":"PSYC","catalog":"311","title":"Human Cognition and the Brain","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"315","title":"Computational Psychology","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"316","title":"Genes and Behaviour","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"317","title":"Behavioural Neuroscience 2","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"318","title":"Introduction to Neuroscience 2","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"319","title":"Computational Models – Cognition","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"320","title":"Introduction to Auditory Cognition","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"322","title":"The Psychology of Bilingualism","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"323","title":"Hormones and Behaviour","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"305","title":"Statistics for Experimental Design","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Required for Honours; take early if planning Honours"},
        ],
      },
      {
        "block_key": "list_b",
        "title": "List B – Social, Health & Developmental Psychology",
        "credits_needed": 3,
        "notes": "3 credits from List B.",
        "courses": [
          {"subject":"PSYC","catalog":"215","title":"Social Psychology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Most popular PSYC elective at McGill"},
          {"subject":"PSYC","catalog":"304","title":"Child Development","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"309","title":"Positive Psychology: Science of Well-Being","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Very accessible; one of the highest-rated PSYC courses"},
          {"subject":"PSYC","catalog":"328","title":"Health Psychology","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"331","title":"Inter-Group Relations","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"332","title":"Introduction to Personality","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"333","title":"Personality and Social Psychology","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"337","title":"Introduction to Psychopathology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Engaging; popular with students from all programs"},
          {"subject":"PSYC","catalog":"339","title":"Introduction to Applied Psychology","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"340","title":"Psychology of Language","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "upper_300",
        "title": "Upper-Level PSYC Electives (300+)",
        "credits_needed": 6,
        "min_level": 300,
        "notes": "6 credits from PSYC courses at 300-level or above.",
        "courses": [
          {"subject":"PSYC","catalog":"307","title":"Clinical Psychology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Great if interested in clinical track"},
          {"subject":"PSYC","catalog":"325","title":"Modern Psychology in Historical Perspective","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"326","title":"Psychological Tests","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"329","title":"Sensorimotor Neuroscience","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"350","title":"Language and the Brain","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"402","title":"Memory and Brain","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"403","title":"Cognitive Neuroscience of Attention","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"404","title":"Human Decision-Making","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Bridges cognitive and social psych; very popular"},
          {"subject":"PSYC","catalog":"406","title":"Neurobiology of Memory","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"408","title":"Neurochemistry and Behaviour","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"410","title":"Advances in Visual Perception","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"412","title":"Music Cognition","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"414","title":"Social Cognition","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"519","title":"Human Learning and Memory","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"532","title":"Advanced Seminar in Psychology of Language","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"542","title":"Consciousness","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"546","title":"Topics in Language Acquisition","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"560","title":"Machine Learning Tools in Psychology","credits":3,"is_required":False,"recommendation_reason":"For students with COMP background; very specialized"},
          {"subject":"PSYC","catalog":"562","title":"Measurement of Psychological Processes","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"563","title":"Multilevel Modelling","credits":3,"is_required":False},
        ],
      },
      {
        "block_key": "free_psyc",
        "title": "Additional PSYC Electives",
        "credits_needed": 12,
        "notes": "12 additional credits in PSYC.",
        "courses": [
          {"subject":"PSYC","catalog":None,"title":"Any PSYC course","credits":3,"is_required":False},
        ],
      },
    ],
  },

  {
    "program_key": "psychology_minor",
    "name": "Psychology – Minor Concentration",
    "program_type": "minor",
    "total_credits": 18,
    "description": "A 18-credit introduction to psychological science for students with a primary interest elsewhere.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/psychology/psychology-minor-concentration-ba/",
    "blocks": [
      {
        "block_key": "required",
        "title": "Required Core",
        "credits_needed": 6,
        "courses": [
          {"subject":"PSYC","catalog":"100","title":"Introduction to Psychology","credits":3,"is_required":True,"recommended":True},
          {"subject":"PSYC","catalog":"204","title":"Introduction to Psychological Statistics","credits":3,"is_required":True},
        ],
      },
      {
        "block_key": "electives",
        "title": "PSYC Electives",
        "credits_needed": 12,
        "notes": "12 credits of PSYC courses; at least one course at 300+ level.",
        "min_level": None,
        "courses": [
          {"subject":"PSYC","catalog":"211","title":"Intro to Behavioural Neuroscience","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"215","title":"Social Psychology","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":"304","title":"Child Development","credits":3,"is_required":False},
          {"subject":"PSYC","catalog":"337","title":"Introduction to Psychopathology","credits":3,"is_required":False,"recommended":True},
          {"subject":"PSYC","catalog":None,"title":"Any PSYC course at 300+ level","credits":3,"is_required":False},
        ],
      },
    ],
  },

  # ──────────────────────────────────────────────────────────────────
  # SOCIOLOGY
  # ──────────────────────────────────────────────────────────────────
  {
    "program_key": "sociology_major",
    "name": "Sociology – Major Concentration",
    "program_type": "major",
    "total_credits": 36,
    "description": (
      "Gives students a comprehensive understanding of sociology. "
      "Required courses (SOCI 210, 211, 330, 350) must be taken at McGill."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/sociology/sociology-major-concentration-ba/",
    "blocks": [
      {
        "block_key": "required",
        "title": "Required Courses",
        "credits_needed": 12,
        "notes": "All four required; SOCI 350 can be replaced by equivalent stats course (ECON 227D, PSYC 204, etc.) but must be replaced by another SOCI 300+ course.",
        "courses": [
          {"subject":"SOCI","catalog":"210","title":"Sociological Perspectives","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Take U1 Fall; foundational intro"},
          {"subject":"SOCI","catalog":"211","title":"Sociological Inquiry","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Methods core; take alongside 210"},
          {"subject":"SOCI","catalog":"330","title":"Sociological Theory","credits":3,"is_required":True,"recommended":True,"recommendation_reason":"Marx, Weber, Durkheim — essential"},
          {"subject":"SOCI","catalog":"350","title":"Statistics in Social Research","credits":3,"is_required":True,"notes":"Equivalents: ECON 227D, PSYC 204, MATH 203, MGCR 271 etc."},
        ],
      },
      {
        "block_key": "complementary",
        "title": "Complementary Courses (24 credits)",
        "credits_needed": 24,
        "min_credits_400": 3,
        "max_credits_200": 9,
        "notes": "At least 3 credits at 400-level; max 9 credits at 200-level. Max 6 credits from SOCI 340/341/342/343/440/441/442/443. 500-level seminars open to Major students in their final year.",
        "courses": [
          # ── 200-level options ──
          {"subject":"SOCI","catalog":"230","title":"Self and Society","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Popular; pairs well with 210"},
          {"subject":"SOCI","catalog":"234","title":"Sociology of Gender","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"244","title":"Social Problems","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"245","title":"Population and Society","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"250","title":"Social Inequality","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"254","title":"Development and Underdevelopment","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"260","title":"Socialization","credits":3,"is_required":False},
          # ── Institutions, Deviance & Culture ──
          {"subject":"SOCI","catalog":"300","title":"Sociology of Sexualities","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"302","title":"Health and Illness","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"303","title":"Sociology of Mental Health","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"One of the most popular SOCI courses; very accessible"},
          {"subject":"SOCI","catalog":"305","title":"Sociology of the Media","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"310","title":"Medical Sociology","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Covers medicine & society — great for pre-med adjacent tracks"},
          {"subject":"SOCI","catalog":"315","title":"Sociology of Literature","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"325","title":"Sociology of Science","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"340","title":"Criminology","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"341","title":"Punishment and Prisons","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"342","title":"Gender, Deviance and Social Control","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"343","title":"Surveillance in Modern Society","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"348","title":"Sociology of the Family","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"349","title":"Deviance and Social Control","credits":3,"is_required":False},
          # ── Politics & Social Change ──
          {"subject":"SOCI","catalog":"320","title":"Contemporary Social Movements","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"322","title":"Comparative Migration and Citizenship","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"323","title":"Colonialism and Society","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"324","title":"Sociology of Citizenship","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"326","title":"Political Sociology","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"327","title":"Dynamics of Industrial Societies","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"328","title":"Health and Development","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"329","title":"Post-Socialist Societies","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"331","title":"Emerging Democratic States","credits":3,"is_required":False},
          # ── Social Stratification: Class, Ethnicity & Gender ──
          {"subject":"SOCI","catalog":"360","title":"Urban Sociology","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"362","title":"Sociology of Ethnic Relations","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"363","title":"Gender and the State","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"364","title":"Gender and Globalization","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"365","title":"Health and Development","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"367","title":"Sociology of Population","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"368","title":"Migration Governance and Stratification","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"370","title":"Social Stratification","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"372","title":"Sociology of Aging and the Life Course","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"374","title":"Neighborhoods and Inequality","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"376","title":"Suspect Minorities in Canada","credits":3,"is_required":False},
          # ── Work, Organizations & Economy ──
          {"subject":"SOCI","catalog":"380","title":"Networks and Social Structures","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"382","title":"Technology and Society","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"384","title":"Sociology of the Welfare State","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"385","title":"Sociology of Work and Industry","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"387","title":"Organizations","credits":3,"is_required":False},
          # ── 400-level seminars (satisfy the 3-credit 400+ requirement) ──
          {"subject":"SOCI","catalog":"440","title":"Advanced Seminar: Institutions, Deviance & Culture","credits":3,"is_required":False,"recommended":True,"recommendation_reason":"Satisfies 400-level requirement; intensive seminar format"},
          {"subject":"SOCI","catalog":"441","title":"Advanced Seminar: Politics & Social Change","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"442","title":"Advanced Seminar: Stratification – Class, Ethnicity & Gender","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"443","title":"Advanced Seminar: Work, Organizations & Economy","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":"450","title":"Urban Ethnography","credits":3,"is_required":False,"recommended":True},
        ],
      },
    ],
  },

  {
    "program_key": "sociology_minor",
    "name": "Sociology – Minor Concentration",
    "program_type": "minor",
    "total_credits": 18,
    "description": "Gives students a basic understanding of sociology. Required courses must be taken at McGill.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/programs/sociology/sociology-minor-concentration-ba/",
    "blocks": [
      {
        "block_key": "required",
        "title": "Required Courses",
        "credits_needed": 9,
        "notes": "SOCI 210, 211 required. Plus either SOCI 330 or SOCI 350.",
        "courses": [
          {"subject":"SOCI","catalog":"210","title":"Sociological Perspectives","credits":3,"is_required":True,"recommended":True},
          {"subject":"SOCI","catalog":"211","title":"Sociological Inquiry","credits":3,"is_required":True,"recommended":True},
          {"subject":"SOCI","catalog":"330","title":"Classical Sociological Theory OR","credits":3,"is_required":False,"choose_from_group":"theory_or_stats","choose_n_credits":3,"recommended":True},
          {"subject":"SOCI","catalog":"350","title":"Statistics in Social Research","credits":3,"is_required":False,"choose_from_group":"theory_or_stats","choose_n_credits":3},
        ],
      },
      {
        "block_key": "complementary",
        "title": "Complementary Courses",
        "credits_needed": 9,
        "notes": "9 credits of SOCI; at least one course at 300-level or above.",
        "courses": [
          {"subject":"SOCI","catalog":"230","title":"Self and Society","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"250","title":"Social Inequality","credits":3,"is_required":False,"recommended":True},
          {"subject":"SOCI","catalog":"310","title":"Medical Sociology","credits":3,"is_required":False},
          {"subject":"SOCI","catalog":None,"title":"Any SOCI course at 300+ level","credits":3,"is_required":False},
        ],
      },
    ],
  },

]
