"""
McGill Faculty of Science – Degree Requirements Part 2
Chemistry, Biology, Biochemistry, Microbiology & Immunology
"""

SCIENCE_PROGRAMS_PART2 = [

  # ══════════════════════════════════════════════════════════════════════
  #  CHEMISTRY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "chemistry_minor_bsc",
    "name": "Chemistry Minor (B.Sc.) (24 credits)",
    "program_type": "minor",
    "faculty": "Faculty of Science",
    "total_credits": 24,
    "description": "May be combined with any primary program in the Faculty of Science other than Chemistry programs.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-minor-bsc/",
    "blocks": [
      {
        "block_key": "chem_minor_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "CHEM 110/120 may be replaced by CHEM 115/123 (Science stream) for students with advanced standing.",
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "120", "title": "General Chemistry 2",                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Organic Chemistry 2",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Analytical Chemistry",    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "314", "title": "Physical Chemistry: Thermodynamics",   "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "chem_minor_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 6,
        "courses_needed": None,
        "group_name": None,
        "notes": "6 credits from CHEM 300+.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "310", "title": "Advanced Inorganic Chemistry",         "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "315", "title": "Physical Chemistry: Quantum Mechanics","credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "322", "title": "Organic Chemistry 3",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "323", "title": "Organic Chemistry 4",                  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "325", "title": "Analytical Chemistry",                 "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "340", "title": "Computational Chemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "chemistry_major_bsc",
    "name": "Chemistry Major (B.Sc.) (59 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 59,
    "description": "Provides a broad and thorough foundation in all major areas of chemistry including organic, inorganic, physical, and analytical chemistry.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-major-bsc/",
    "blocks": [
      {
        "block_key": "chem_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 53,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Physical Chemistry 1: Thermodynamics",        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "242", "title": "Organic Chemistry 1 for Chemistry and Biochemistry",       "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "252", "title": "Organic Chemistry 2 for Chemistry and Biochemistry",       "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "267", "title": "Introductory Chemical Analysis",                           "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "273", "title": "Introductory Physical Chemistry 2: Kinetics and Methods",  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "281", "title": "Inorganic Chemistry 1",                                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "302", "title": "Introductory Organic Chemistry 3",                         "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "332", "title": "Biological Chemistry",                                     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "345", "title": "Introduction to Quantum Chemistry",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "355", "title": "Applications of Quantum Chemistry",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "365", "title": "Statistical Thermodynamics",                               "credits": 2, "is_required": True},
          {"subject": "CHEM", "catalog": "367", "title": "Instrumental Analysis 1",                                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "377", "title": "Instrumental Analysis 2",                                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "381", "title": "Inorganic Chemistry 2",                                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "392", "title": "Experimental Chemistry 1",                                 "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "493", "title": "Advanced Physical Chemistry Laboratory",                   "credits": 2, "is_required": True},
          {"subject": "MATH", "catalog": "222", "title": "Calculus 3",                                               "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "242", "title": "Electricity and Magnetism",                                "credits": 2, "is_required": True},
        ],
      },
      {
        "block_key": "chem_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 6,
        "courses_needed": None,
        "group_name": None,
        "notes": "6 credits from CHEM 400+, or MATH 315 (Ordinary Differential Equations, 3 credits) plus 3 credits from CHEM 400+.",
        "sort_order": 2,
        "courses": [
          {"subject": "MATH", "catalog": "315", "title": "Ordinary Differential Equations",     "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "chemistry_honours_bsc",
    "name": "Chemistry Honours (B.Sc.) (71 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 71,
    "description": "Designed for students with high aptitude in chemistry who intend to pursue graduate studies or a research career. Requires minimum CGPA 3.00. Includes a research project.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/chemistry/chemistry-honours-bsc/",
    "blocks": [
      {
        "block_key": "chem_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 53,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "CHEM", "catalog": "213", "title": "Introductory Physical Chemistry 1: Thermodynamics",        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "242", "title": "Organic Chemistry 1 for Chemistry and Biochemistry",       "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "252", "title": "Organic Chemistry 2 for Chemistry and Biochemistry",       "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "267", "title": "Introductory Chemical Analysis",                           "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "273", "title": "Introductory Physical Chemistry 2: Kinetics and Methods",  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "281", "title": "Inorganic Chemistry 1",                                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "302", "title": "Introductory Organic Chemistry 3",                         "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "332", "title": "Biological Chemistry",                                     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "345", "title": "Introduction to Quantum Chemistry",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "355", "title": "Applications of Quantum Chemistry",                        "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "365", "title": "Statistical Thermodynamics",                               "credits": 2, "is_required": True},
          {"subject": "CHEM", "catalog": "367", "title": "Instrumental Analysis 1",                                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "377", "title": "Instrumental Analysis 2",                                  "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "381", "title": "Inorganic Chemistry 2",                                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "392", "title": "Experimental Chemistry 1",                                 "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "493", "title": "Advanced Physical Chemistry Laboratory",                   "credits": 2, "is_required": True},
          {"subject": "MATH", "catalog": "222", "title": "Calculus 3",                                               "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "242", "title": "Electricity and Magnetism",                                "credits": 2, "is_required": True},
        ],
      },
      {
        "block_key": "chem_hon_research",
        "title": "Honours Research",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one research track (6 credits).",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "470", "title": "Research Project 1",                   "credits": 6, "is_required": False},
          {"subject": "CHEM", "catalog": "480", "title": "Undergraduate Research Project 2",      "credits": 6, "is_required": False},
        ],
      },
      {
        "block_key": "chem_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 12,
        "courses_needed": None,
        "group_name": None,
        "notes": "12 credits: 6 credits from CHEM 300+ (or MATH 315 + 3 credits CHEM 300+), plus 6 credits from CHEM 400+.",
        "sort_order": 3,
        "courses": [
          {"subject": "MATH", "catalog": "315", "title": "Ordinary Differential Equations",       "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  BIOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "biology_liberal_bsc",
    "name": "Biology – Liberal Program Core Science Component (B.Sc.) (47 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 47,
    "description": "Provides an introduction to molecular, cellular, organismal, and evolutionary biology with supporting courses in chemistry and computing.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-liberal-program-core-science-component-bsc/",
    "blocks": [
      {
        "block_key": "biol_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 24,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",                "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "205", "title": "Functional Biology of Plants and Animals",   "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "206", "title": "Methods in Biology",                         "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "215", "title": "Introduction to Ecology and Evolution",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "216", "title": "Biology of Behaviour",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "302", "title": "Fundamentals of Genetics and Genomics",      "credits": 3, "is_required": True},
          {"subject": "COMP", "catalog": "204", "title": "Computer Programming for Life Sciences",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "biol_lib_chem",
        "title": "Chemistry Requirement",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one chemistry course.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1",  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",          "credits": 4, "is_required": False},
        ],
      },
      {
        "block_key": "biol_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 19,
        "courses_needed": None,
        "group_name": None,
        "notes": "19 credits from BIOL 300–500 level courses.",
        "sort_order": 3,
        "courses": [
          {"subject": "BIOL", "catalog": "300", "title": "Molecular Biology of the Gene",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "303", "title": "Developmental Biology",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Evolution",                                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "305", "title": "Animal Diversity",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Neural Basis of Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Behavioural Ecology",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Ecological Dynamics",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "311", "title": "Advanced Methods in Organismal Biology",     "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "313", "title": "Eukaryotic Cell Biology",                    "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "430", "title": "Evolutionary Genetics",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "432", "title": "Conservation Biology",                       "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "449", "title": "Animal Behaviour",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "465", "title": "Biodiversity and Macroecology",              "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biology_major_bsc",
    "name": "Biology Major (B.Sc.) (59 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 59,
    "description": "Covers cell/molecular biology, genetics, evolution, ecology, and physiology. Students may focus on Cell/Molecular or Organismal biology through choice of complementary courses.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-major-bsc/",
    "blocks": [
      {
        "block_key": "biol_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 31,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",                "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "205", "title": "Functional Biology of Plants and Animals",   "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "206", "title": "Methods in Biology",                         "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "215", "title": "Introduction to Ecology and Evolution",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "216", "title": "Biology of Behaviour",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301", "title": "Cell and Molecular Laboratory",              "credits": 4, "is_required": True},
          {"subject": "BIOL", "catalog": "302", "title": "Fundamentals of Genetics and Genomics",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "311", "title": "Advanced Methods in Organismal Biology",     "credits": 3, "is_required": True},
          {"subject": "COMP", "catalog": "204", "title": "Computer Programming for Life Sciences",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "biol_major_chem",
        "title": "Chemistry Requirement",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one chemistry course.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1",  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",          "credits": 4, "is_required": False},
        ],
      },
      {
        "block_key": "biol_major_block_a",
        "title": "Block A – Ecology and Evolution",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block A.",
        "sort_order": 3,
        "courses": [
          {"subject": "BIOL", "catalog": "304", "title": "Evolution",                                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "305", "title": "Animal Diversity",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Ecological Dynamics",                        "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_major_block_b",
        "title": "Block B – Molecular and Cellular",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block B.",
        "sort_order": 4,
        "courses": [
          {"subject": "BIOL", "catalog": "300", "title": "Molecular Biology of the Gene",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "303", "title": "Developmental Biology",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "313", "title": "Eukaryotic Cell Biology",                    "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_major_block_c",
        "title": "Block C – Neurobiology and Behaviour",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block C.",
        "sort_order": 5,
        "courses": [
          {"subject": "BIOL", "catalog": "306", "title": "Neural Basis of Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Behavioural Ecology",                        "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_major_elec",
        "title": "Complementary Electives",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from BIOL 300–500. At least 6 credits must be at the 400–500 level. Up to 6 credits may be research or non-BIOL science courses with adviser approval.",
        "sort_order": 6,
        "courses": [
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "426", "title": "Plant Physiology",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "430", "title": "Evolutionary Genetics",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "432", "title": "Conservation Biology",                       "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "441", "title": "Population Genetics",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "449", "title": "Animal Behaviour",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "465", "title": "Biodiversity and Macroecology",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "478", "title": "Developmental Genetics",                     "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biology_honours_bsc",
    "name": "Biology Honours (B.Sc.) (72 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 72,
    "description": "Provides advanced training in biology for students who plan to pursue graduate studies or research. Includes an independent research project.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biology/biology-honours-bsc/",
    "blocks": [
      {
        "block_key": "biol_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 35,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                          "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",                "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "205", "title": "Functional Biology of Plants and Animals",   "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "206", "title": "Methods in Biology",                         "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "215", "title": "Introduction to Ecology and Evolution",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "216", "title": "Biology of Behaviour",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301", "title": "Cell and Molecular Laboratory",              "credits": 4, "is_required": True},
          {"subject": "BIOL", "catalog": "302", "title": "Fundamentals of Genetics and Genomics",      "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "311", "title": "Advanced Methods in Organismal Biology",     "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "499D1", "title": "Honours Seminar in Biology",               "credits": 2, "is_required": True},
          {"subject": "BIOL", "catalog": "499D2", "title": "Honours Seminar in Biology",               "credits": 2, "is_required": True},
          {"subject": "COMP", "catalog": "204", "title": "Computer Programming for Life Sciences",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "biol_hon_chem",
        "title": "Chemistry Requirement",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one chemistry course.",
        "sort_order": 2,
        "courses": [
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1",  "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",          "credits": 4, "is_required": False},
        ],
      },
      {
        "block_key": "biol_hon_block_a",
        "title": "Block A – Ecology and Evolution",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block A.",
        "sort_order": 3,
        "courses": [
          {"subject": "BIOL", "catalog": "304", "title": "Evolution",                                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "305", "title": "Animal Diversity",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "308", "title": "Ecological Dynamics",                        "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_hon_block_b",
        "title": "Block B – Molecular and Cellular",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block B.",
        "sort_order": 4,
        "courses": [
          {"subject": "BIOL", "catalog": "300", "title": "Molecular Biology of the Gene",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "303", "title": "Developmental Biology",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "313", "title": "Eukaryotic Cell Biology",                    "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_hon_block_c",
        "title": "Block C – Neurobiology and Behaviour",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one course from Block C.",
        "sort_order": 5,
        "courses": [
          {"subject": "BIOL", "catalog": "306", "title": "Neural Basis of Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Behavioural Ecology",                        "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "biol_hon_research",
        "title": "Honours Research",
        "block_type": "choose_courses",
        "credits_needed": None,
        "courses_needed": 1,
        "group_name": None,
        "notes": "Choose one research track: BIOL 479D1+D2 (9 credits) or BIOL 480D1+D2 (12 credits).",
        "sort_order": 6,
        "courses": [
          {"subject": "BIOL", "catalog": "479D1", "title": "Honours Research 1",                       "credits": 5, "is_required": False},
          {"subject": "BIOL", "catalog": "479D2", "title": "Honours Research 2",                       "credits": 4, "is_required": False},
          {"subject": "BIOL", "catalog": "480D1", "title": "Extended Honours Research 1",              "credits": 6, "is_required": False},
          {"subject": "BIOL", "catalog": "480D2", "title": "Extended Honours Research 2",              "credits": 6, "is_required": False},
        ],
      },
      {
        "block_key": "biol_hon_elec",
        "title": "Complementary Electives",
        "block_type": "choose_credits",
        "credits_needed": 12,
        "courses_needed": None,
        "group_name": None,
        "notes": "12–15 credits from BIOL 300–500. At least 6 credits must be at the 400–500 level. Up to 6 credits may be from other science departments with adviser approval.",
        "sort_order": 7,
        "courses": [
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                         "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "426", "title": "Plant Physiology",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "430", "title": "Evolutionary Genetics",                      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "432", "title": "Conservation Biology",                       "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "441", "title": "Population Genetics",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "449", "title": "Animal Behaviour",                           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "465", "title": "Biodiversity and Macroecology",              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "478", "title": "Developmental Genetics",                     "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  BIOCHEMISTRY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "biochemistry_liberal_bsc",
    "name": "Biochemistry – Liberal Program Core Science Component (B.Sc.) (47 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 47,
    "description": "Provides a foundation in biochemistry with supporting courses in biology, chemistry, physics, and mathematics.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "bioc_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 35,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOC", "catalog": "212", "title": "Molecular Mechanisms of Cell Function", "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "220", "title": "Laboratory Methods in Biochemistry and Molecular Biology 1","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry of Macromolecules",       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "320", "title": "Laboratory Methods in Biochemistry and Molecular Biology 2","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "302", "title": "Introductory Organic Chemistry 3",     "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "bioc_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 12,
        "courses_needed": None,
        "group_name": None,
        "notes": "12 credits from approved BIOC, BIOL, CHEM, and related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOC", "catalog": "450", "title": "Protein Structure and Function",       "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "454", "title": "Nucleic Acids",                        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "214", "title": "Physical Chemistry/Biological Sciences 2","credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "362", "title": "Advanced Organic Chemistry Laboratory","credits": 2, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biochemistry_major_bsc",
    "name": "Biochemistry Major (B.Sc.) (64 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 64,
    "description": "Integrates molecular biology, cell biology, and chemistry to understand biological processes at the molecular level.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-major-bsc/",
    "blocks": [
      {
        "block_key": "bioc_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 51,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOC", "catalog": "212", "title": "Molecular Mechanisms of Cell Function", "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "220", "title": "Laboratory Methods in Biochemistry and Molecular Biology 1","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "242", "title": "Organic Chemistry 1 for Chemistry and Biochemistry","credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "252", "title": "Organic Chemistry 2 for Chemistry and Biochemistry","credits": 4, "is_required": True},
          {"subject": "ANAT", "catalog": "262", "title": "Introductory Molecular and Cell Biology","credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry of Macromolecules",       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "320", "title": "Laboratory Methods in Biochemistry and Molecular Biology 2","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "214", "title": "Physical Chemistry/Biological Sciences 2","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "302", "title": "Introductory Organic Chemistry 3",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "362", "title": "Advanced Organic Chemistry Laboratory","credits": 2, "is_required": True},
          {"subject": "BIOC", "catalog": "450", "title": "Protein Structure and Function",       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "454", "title": "Nucleic Acids",                        "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "bioc_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 13,
        "courses_needed": None,
        "group_name": None,
        "notes": "13 credits from approved BIOC, BIOL, CHEM, and related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOC", "catalog": "404", "title": "Biophysical Methods in Biochemistry", "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                             "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "biochemistry_honours_bsc",
    "name": "Biochemistry Honours (B.Sc.) (73 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 73,
    "description": "For students planning to pursue graduate study or a research career in biochemistry, molecular biology, or related fields.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/biochemistry/biochemistry-honours-bsc/",
    "blocks": [
      {
        "block_key": "bioc_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 58,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOC", "catalog": "212", "title": "Molecular Mechanisms of Cell Function", "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "220", "title": "Laboratory Methods in Biochemistry and Molecular Biology 1","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "204", "title": "Physical Chemistry/Biological Sciences 1","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "242", "title": "Organic Chemistry 1 for Chemistry and Biochemistry","credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "252", "title": "Organic Chemistry 2 for Chemistry and Biochemistry","credits": 4, "is_required": True},
          {"subject": "ANAT", "catalog": "262", "title": "Introductory Molecular and Cell Biology","credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry of Macromolecules",       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "320", "title": "Laboratory Methods in Biochemistry and Molecular Biology 2","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "214", "title": "Physical Chemistry/Biological Sciences 2","credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "302", "title": "Introductory Organic Chemistry 3",     "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "362", "title": "Advanced Organic Chemistry Laboratory","credits": 2, "is_required": True},
          {"subject": "BIOC", "catalog": "404", "title": "Biophysical Methods in Biochemistry", "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "450", "title": "Protein Structure and Function",       "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "454", "title": "Nucleic Acids",                        "credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "462", "title": "Research Laboratory in Biochemistry",  "credits": 6, "is_required": True},
        ],
      },
      {
        "block_key": "bioc_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from approved upper-level BIOC, BIOL, or CHEM courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "307", "title": "Techniques in Molecular Biology",      "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "402", "title": "Structural Biochemistry",              "credits": 3, "is_required": False},
          {"subject": "CHEM", "catalog": "404", "title": "Medicinal Chemistry",                  "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  MICROBIOLOGY & IMMUNOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "microbiology_immunology_major_bsc",
    "name": "Microbiology and Immunology Major (B.Sc.) (66 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 66,
    "description": "Studies microorganisms (bacteria, viruses, fungi, parasites) and the immune system, with laboratory work in microbial techniques.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/microbiology-immunology/microbiology-immunology-major-bsc/",
    "blocks": [
      {
        "block_key": "mibi_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 48,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "MIMM", "catalog": "211", "title": "Introductory Microbiology",            "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "212", "title": "Laboratory in Microbiology",           "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "214", "title": "Introductory Immunology: Elements of Immunity","credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "301", "title": "Scientific Writing Skills in MIMM",   "credits": 1, "is_required": True},
          {"subject": "MIMM", "catalog": "314", "title": "Intermediate Immunology",              "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "323", "title": "Microbial Physiology",                 "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "324", "title": "Fundamental Virology",                 "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "384", "title": "Molecular Microbiology Laboratory",    "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "385", "title": "Laboratory in Immunology",             "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "413", "title": "Parasitology",                         "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "mibi_major_cell_choice",
        "title": "Cell Biology Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Cell Biology Choice",
        "notes": "Choose BIOC 212 or BIOL 201.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOC", "catalog": "212", "title": "Molecular Mechanisms of Cell Function","credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "mibi_major_stats_choice",
        "title": "Statistics Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Statistics Choice",
        "notes": "One statistics course from the approved list.",
        "sort_order": 3,
        "courses": [
          {"subject": "BIOL", "catalog": "373", "title": "Biometry",                               "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "203", "title": "Statistics for Life Sciences",         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "204", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "mibi_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from MIMM 400+ or approved upper-level biology/biochemistry courses.",
        "sort_order": 4,
        "courses": [
          {"subject": "MIMM", "catalog": "411", "title": "Medical Microbiology",                 "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "414", "title": "Bacterial Pathogenesis",               "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "430", "title": "Host-Pathogen Interactions",           "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "465", "title": "Bacterial Pathogenesis",               "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "466", "title": "Viral Pathogenesis",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "404", "title": "Functional Genomics",                  "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "450", "title": "Protein Structure and Function",       "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "microbiology_immunology_honours_bsc",
    "name": "Microbiology and Immunology Honours (B.Sc.) (72 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 72,
    "description": "Provides advanced training in microbiology and immunology for students planning graduate study or research careers.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/microbiology-immunology/microbiology-immunology-honours-bsc/",
    "blocks": [
      {
        "block_key": "mibi_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 48,
        "courses_needed": None,
        "group_name": None,
        "notes": "Same required courses as the Major.",
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "MIMM", "catalog": "211", "title": "Introductory Microbiology",            "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "212", "title": "Laboratory in Microbiology",           "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "214", "title": "Introductory Immunology: Elements of Immunity","credits": 3, "is_required": True},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "301", "title": "Scientific Writing Skills in MIMM",   "credits": 1, "is_required": True},
          {"subject": "MIMM", "catalog": "314", "title": "Intermediate Immunology",              "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "323", "title": "Microbial Physiology",                 "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "324", "title": "Fundamental Virology",                 "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "384", "title": "Molecular Microbiology Laboratory",    "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "385", "title": "Laboratory in Immunology",             "credits": 3, "is_required": True},
          {"subject": "MIMM", "catalog": "413", "title": "Parasitology",                         "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "mibi_hon_cell_choice",
        "title": "Cell Biology Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Cell Biology Choice",
        "notes": "Choose BIOC 212 or BIOL 201.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOC", "catalog": "212", "title": "Molecular Mechanisms of Cell Function","credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "201", "title": "Cell Biology and Metabolism",          "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "mibi_hon_stats_choice",
        "title": "Statistics Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Statistics Choice",
        "notes": "One statistics course from the approved list.",
        "sort_order": 3,
        "courses": [
          {"subject": "BIOL", "catalog": "373", "title": "Biometry",                             "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "203", "title": "Statistics for Life Sciences",         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "204", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "mibi_hon_research",
        "title": "Honours Research Project",
        "block_type": "choose_courses",
        "credits_needed": 12,
        "courses_needed": 1,
        "group_name": "Honours Research",
        "notes": "MIMM 501D1/D2 or MIMM 502D1/D2.",
        "sort_order": 4,
        "courses": [
          {"subject": "MIMM", "catalog": "501D1", "title": "Honours Research Project 1",         "credits": 6, "is_required": False},
          {"subject": "MIMM", "catalog": "501D2", "title": "Honours Research Project 1",         "credits": 6, "is_required": False},
          {"subject": "MIMM", "catalog": "502D1", "title": "Honours Research Project 2",         "credits": 6, "is_required": False},
          {"subject": "MIMM", "catalog": "502D2", "title": "Honours Research Project 2",         "credits": 6, "is_required": False},
        ],
      },
      {
        "block_key": "mibi_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 6,
        "courses_needed": None,
        "group_name": None,
        "notes": "6 credits from MIMM 400+ or approved upper-level biology/biochemistry courses.",
        "sort_order": 5,
        "courses": [
          {"subject": "MIMM", "catalog": "411", "title": "Medical Microbiology",                 "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "414", "title": "Bacterial Pathogenesis",               "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "420", "title": "Advanced Immunology",                  "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "425", "title": "Molecular Virology",                   "credits": 3, "is_required": False},
          {"subject": "MIMM", "catalog": "430", "title": "Host-Pathogen Interactions",           "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "450", "title": "Protein Structure and Function",       "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  ANATOMY & CELL BIOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "anatomy_cell_biology_liberal_bsc",
    "name": "Anatomy and Cell Biology – Liberal Program Core Science Component (B.Sc.) (48 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 48,
    "description": "Introduction to human gross anatomy, histology, cell biology, and neuroscience.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/anatomy-cell-biology/anatomy-cell-biology-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "anat_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 29,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ANAT", "catalog": "212", "title": "Molecular Mechanisms of Cell Function","credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "214", "title": "Systemic Human Anatomy",               "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",    "credits": 4, "is_required": True},
          {"subject": "ANAT", "catalog": "262", "title": "Introductory Molecular and Cell Biology","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "PHGY", "catalog": "209", "title": "Mammalian Physiology 1",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "210", "title": "Mammalian Physiology 2",               "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "anat_lib_stats_choice",
        "title": "Statistics Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Statistics Choice",
        "notes": "One statistics course from the approved list.",
        "sort_order": 2,
        "courses": [
          {"subject": "MATH", "catalog": "203", "title": "Statistics for Life Sciences",         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "204", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "anat_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 16,
        "courses_needed": None,
        "group_name": None,
        "notes": "16 credits from ANAT 300+ or approved related courses.",
        "sort_order": 3,
        "courses": [
          {"subject": "ANAT", "catalog": "411", "title": "Neuroanatomy",                         "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "415", "title": "Developmental Anatomy",                "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "420", "title": "Molecular and Cellular Neuroscience",  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                   "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "312", "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "anatomy_cell_biology_major_bsc",
    "name": "Anatomy and Cell Biology Major (B.Sc.) (67 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 67,
    "description": "Studies human anatomy and cell biology with laboratory components in histology and gross anatomy dissection.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/anatomy-cell-biology/anatomy-cell-biology-major-bsc/",
    "blocks": [
      {
        "block_key": "anat_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 40,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ANAT", "catalog": "212", "title": "Molecular Mechanisms of Cell Function","credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "214", "title": "Systemic Human Anatomy",               "credits": 3, "is_required": True},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",    "credits": 4, "is_required": True},
          {"subject": "ANAT", "catalog": "262", "title": "Introductory Molecular and Cell Biology","credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202", "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301", "title": "Cell and Molecular Laboratory",        "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222", "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "MIMM", "catalog": "214", "title": "Introductory Immunology: Elements of Immunity","credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "209", "title": "Mammalian Physiology 1",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "210", "title": "Mammalian Physiology 2",               "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "anat_major_stats_choice",
        "title": "Statistics Course (choose 1)",
        "block_type": "choose_courses",
        "credits_needed": 3,
        "courses_needed": 1,
        "group_name": "Statistics Choice",
        "notes": "One statistics course from the approved list.",
        "sort_order": 2,
        "courses": [
          {"subject": "BIOL", "catalog": "373", "title": "Biometry",                             "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "203", "title": "Statistics for Life Sciences",         "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "204", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "anat_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 24,
        "courses_needed": None,
        "group_name": None,
        "notes": "24 credits from ANAT 400+ or approved related courses.",
        "sort_order": 3,
        "courses": [
          {"subject": "ANAT", "catalog": "411", "title": "Neuroanatomy",                         "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "415", "title": "Developmental Anatomy",                "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "420", "title": "Molecular and Cellular Neuroscience",  "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "411", "title": "Cell Regulation and Signaling",        "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "311", "title": "Channels, Synapses and Hormones",      "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "312", "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "313", "title": "Blood, Gastrointestinal, and Immune Systems Physiology","credits": 3, "is_required": False},
        ],
      },
    ],
  },

]  # END SCIENCE_PROGRAMS_PART2
