"""
McGill Faculty of Science – Degree Requirements Part 3
Physiology, Neuroscience, Psychology B.Sc.,
Earth & Planetary Sciences, Atmospheric & Oceanic Sciences, Cognitive Science
"""

SCIENCE_PROGRAMS_PART3 = [

  # ══════════════════════════════════════════════════════════════════════
  #  PHYSIOLOGY
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "physiology_liberal_bsc",
    "name": "Physiology – Liberal Program Core Science Component (B.Sc.) (48 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 48,
    "description": "Introduction to animal physiology with supporting courses in chemistry and biology.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/physiology/physiology-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "phgy_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 33,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200",  "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202",  "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301",  "title": "Cell and Molecular Laboratory",        "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "212",  "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222",  "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "PHGY", "catalog": "200",  "title": "Cutting-Edge Research in Physiology",  "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "209",  "title": "Mammalian Physiology 1",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "210",  "title": "Mammalian Physiology 2",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "212",  "title": "Introductory Physiology Laboratory 1", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "213",  "title": "Introductory Physiology Laboratory 2", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "312",  "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "313",  "title": "Blood, Gastrointestinal, and Immune Systems Physiology","credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "phgy_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from PHGY 400+ or approved related science courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "PHGY", "catalog": "311", "title": "Channels, Synapses and Hormones",       "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "314", "title": "Integrative Neuroscience",              "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "351", "title": "Research Techniques: Physiology",       "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",                "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",     "credits": 4, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "physiology_major_bsc",
    "name": "Physiology Major (B.Sc.) (66 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 66,
    "description": "Covers mammalian systems physiology including cardiovascular, respiratory, renal, endocrine, and neurophysiology.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/physiology/physiology-major-bsc/",
    "blocks": [
      {
        "block_key": "phgy_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 35,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200",  "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202",  "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301",  "title": "Cell and Molecular Laboratory",        "credits": 4, "is_required": True},
          {"subject": "BIOC", "catalog": "311",  "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212",  "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222",  "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "PHGY", "catalog": "209",  "title": "Mammalian Physiology 1",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "210",  "title": "Mammalian Physiology 2",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "212",  "title": "Introductory Physiology Laboratory 1", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "213",  "title": "Introductory Physiology Laboratory 2", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "312",  "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "313",  "title": "Blood, Gastrointestinal, and Immune Systems Physiology","credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "phgy_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 31,
        "courses_needed": None,
        "group_name": None,
        "notes": "31 credits from PHGY 300+ or approved related science courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "PHGY", "catalog": "311", "title": "Channels, Synapses and Hormones",       "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "314", "title": "Integrative Neuroscience",              "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "351", "title": "Research Techniques: Physiology",       "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "411", "title": "Advanced Mammalian Physiology",         "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "420", "title": "Cardiovascular Physiology",             "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "450", "title": "Endocrine Physiology",                  "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",     "credits": 4, "is_required": False},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry of Macromolecules",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                              "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "physiology_honours_bsc",
    "name": "Physiology Honours (B.Sc.) (75 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 75,
    "description": "For students planning graduate study in physiology or biomedical sciences. Includes an independent research project.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/physiology/physiology-honours-bsc/",
    "blocks": [
      {
        "block_key": "phgy_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 60,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ANAT", "catalog": "261",  "title": "Introduction to Dynamic Histology",    "credits": 4, "is_required": True},
          {"subject": "BIOC", "catalog": "311",  "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200",  "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "202",  "title": "Basic Genetics",                       "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "301",  "title": "Cell and Molecular Laboratory",        "credits": 4, "is_required": True},
          {"subject": "CHEM", "catalog": "222",  "title": "Introductory Organic Chemistry 2",     "credits": 4, "is_required": True},
          {"subject": "PHGY", "catalog": "209",  "title": "Mammalian Physiology 1",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "210",  "title": "Mammalian Physiology 2",               "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "212",  "title": "Introductory Physiology Laboratory 1", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "213",  "title": "Introductory Physiology Laboratory 2", "credits": 1, "is_required": True},
          {"subject": "PHGY", "catalog": "311",  "title": "Channels, Synapses and Hormones",      "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "312",  "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "313",  "title": "Blood, Gastrointestinal, and Immune Systems Physiology","credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "314",  "title": "Integrative Neuroscience",             "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "351",  "title": "Research Techniques: Physiology",      "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "359D1", "title": "Tutorial in Physiology 1",            "credits": 0.5, "is_required": True},
          {"subject": "PHGY", "catalog": "359D2", "title": "Tutorial in Physiology 2",            "credits": 0.5, "is_required": True},
          {"subject": "PHGY", "catalog": "459D1", "title": "Physiology Seminar 1",                "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "459D2", "title": "Physiology Seminar 2",                "credits": 3, "is_required": True},
          {"subject": "PHGY", "catalog": "461D1", "title": "Experimental Physiology 1",           "credits": 4.5, "is_required": True},
          {"subject": "PHGY", "catalog": "461D2", "title": "Experimental Physiology 2",           "credits": 4.5, "is_required": True},
        ],
      },
      {
        "block_key": "phgy_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "15 credits from PHGY 400+ or approved related science courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "PHGY", "catalog": "411", "title": "Advanced Mammalian Physiology",         "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "420", "title": "Cardiovascular Physiology",             "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "450", "title": "Endocrine Physiology",                  "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "312", "title": "Biochemistry of Macromolecules",        "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "304", "title": "Genetics",                              "credits": 3, "is_required": False},
          {"subject": "BIOL", "catalog": "400", "title": "Molecular Genetics",                    "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  NEUROSCIENCE
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "neuroscience_major_bsc",
    "name": "Neuroscience Major (B.Sc.) (65 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 65,
    "description": "Interdisciplinary study of the nervous system drawing on biology, physiology, anatomy, psychology, and chemistry.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/neuroscience/neuroscience-major-bsc/",
    "blocks": [
      {
        "block_key": "nsci_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 20,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "NSCI", "catalog": "200", "title": "Introduction to Neuroscience 1",       "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "201", "title": "Introduction to Neuroscience 2",       "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "300", "title": "Neuroethics",                          "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "400D1", "title": "Neuroscience Seminar 1",             "credits": 0.5, "is_required": True},
          {"subject": "NSCI", "catalog": "400D2", "title": "Neuroscience Seminar 2",             "credits": 0.5, "is_required": True},
          {"subject": "PSYC", "catalog": "311", "title": "Human Cognition and the Brain",        "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "nsci_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 45,
        "courses_needed": None,
        "group_name": None,
        "notes": "45 credits from approved neuroscience-related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "NSCI", "catalog": "410", "title": "Cellular and Molecular Neuroscience",  "credits": 3, "is_required": False},
          {"subject": "NSCI", "catalog": "420", "title": "Systems Neuroscience",                 "credits": 3, "is_required": False},
          {"subject": "NSCI", "catalog": "430", "title": "Cognitive Neuroscience",               "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",    "credits": 4, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "209", "title": "Mammalian Physiology 1",               "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "311", "title": "Channels, Synapses and Hormones",      "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "312", "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "304", "title": "Brain and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "318", "title": "Behavioural Neuroscience 2",           "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                 "credits": 3, "is_required": False},
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "neuroscience_honours_bsc",
    "name": "Neuroscience Honours (B.Sc.) (74 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 74,
    "description": "For students with exceptional aptitude planning graduate studies in neuroscience or related biomedical fields.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/neuroscience/neuroscience-honours-bsc/",
    "blocks": [
      {
        "block_key": "nsci_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 38,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "BIOC", "catalog": "311", "title": "Metabolic Biochemistry",               "credits": 3, "is_required": True},
          {"subject": "BIOL", "catalog": "200", "title": "Molecular Biology",                    "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "212", "title": "Introductory Organic Chemistry 1",     "credits": 4, "is_required": True},
          {"subject": "NSCI", "catalog": "200", "title": "Introduction to Neuroscience 1",       "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "201", "title": "Introduction to Neuroscience 2",       "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "300", "title": "Neuroethics",                          "credits": 3, "is_required": True},
          {"subject": "NSCI", "catalog": "400D1", "title": "Neuroscience Seminar 1",             "credits": 0.5, "is_required": True},
          {"subject": "NSCI", "catalog": "400D2", "title": "Neuroscience Seminar 2",             "credits": 0.5, "is_required": True},
          {"subject": "NSCI", "catalog": "430D1", "title": "Honours Research Project 1",         "credits": 4.5, "is_required": True},
          {"subject": "NSCI", "catalog": "430D2", "title": "Honours Research Project 2",         "credits": 4.5, "is_required": True},
          {"subject": "PHGY", "catalog": "311", "title": "Channels, Synapses and Hormones",      "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "311", "title": "Human Cognition and the Brain",        "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "318", "title": "Behavioural Neuroscience 2",           "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "nsci_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 36,
        "courses_needed": None,
        "group_name": None,
        "notes": "36 credits from approved neuroscience-related courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "NSCI", "catalog": "410", "title": "Cellular and Molecular Neuroscience",  "credits": 3, "is_required": False},
          {"subject": "NSCI", "catalog": "420", "title": "Systems Neuroscience",                 "credits": 3, "is_required": False},
          {"subject": "ANAT", "catalog": "261", "title": "Introduction to Dynamic Histology",    "credits": 4, "is_required": False},
          {"subject": "BIOL", "catalog": "306", "title": "Developmental Biology",                "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "209", "title": "Mammalian Physiology 1",               "credits": 3, "is_required": False},
          {"subject": "PHGY", "catalog": "312", "title": "Respiratory, Renal, and Cardiovascular Physiology","credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "304", "title": "Brain and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                 "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  PSYCHOLOGY (B.Sc.)
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "psychology_liberal_bsc",
    "name": "Psychology – Liberal Program Core Science Component (B.Sc.) (45 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 45,
    "description": "Psychology Liberal B.Sc. – scientific approach to human behaviour and mental processes with supporting science courses.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/psychology/psychology-liberal-program-core-component-bsc/",
    "blocks": [
      {
        "block_key": "psyc_lib_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "PSYC 100 is a prerequisite. Science courses (BIOL, CHEM, PHYS, MATH) are admission prerequisites, not credited within the 45-credit program.",
        "sort_order": 1,
        "courses": [
          {"subject": "PSYC", "catalog": "204", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "211", "title": "Introductory Behavioural Neuroscience","credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "212", "title": "Perception",                           "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "213", "title": "Cognition",                            "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "215", "title": "Social Psychology",                    "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "305", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "psyc_lib_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 27,
        "courses_needed": None,
        "group_name": None,
        "notes": "27 credits from PSYC 300+.",
        "sort_order": 2,
        "courses": [
          {"subject": "PSYC", "catalog": "302", "title": "Physiological Psychology",             "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "304", "title": "Brain and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "305", "title": "Research Methods",                     "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "308", "title": "Motivation",                           "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "311", "title": "Comparative Psychology",               "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "319", "title": "Child Psychopathology",                "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "336", "title": "Language and the Brain",               "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "342", "title": "Sensation",                            "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "350", "title": "Developmental Cognitive Neuroscience", "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "360", "title": "Drugs and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "396", "title": "Honours Thesis 1",                     "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "psychology_major_bsc",
    "name": "Psychology Major (B.Sc.) (54 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 54,
    "description": "Emphasizes the biological bases of behaviour with neuroscience emphasis. Distinct from Psychology B.A. in its scientific and laboratory focus.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/psychology/psychology-major-bsc/",
    "blocks": [
      {
        "block_key": "psyc_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 15,
        "courses_needed": None,
        "group_name": None,
        "notes": "PSYC 100 is a prerequisite, not credited within the 54-credit program.",
        "sort_order": 1,
        "courses": [
          {"subject": "PSYC", "catalog": "211", "title": "Introductory Behavioural Neuroscience","credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "212", "title": "Perception",                           "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "213", "title": "Cognition",                            "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "215", "title": "Social Psychology",                    "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "305", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "psyc_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 39,
        "courses_needed": None,
        "group_name": None,
        "notes": "39 credits from PSYC 300+. At least 9 credits from PSYC 400+.",
        "sort_order": 2,
        "courses": [
          {"subject": "PSYC", "catalog": "302", "title": "Physiological Psychology",             "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "308", "title": "Motivation",                           "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "319", "title": "Child Psychopathology",                "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "336", "title": "Language and the Brain",               "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "342", "title": "Sensation",                            "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "350", "title": "Developmental Cognitive Neuroscience", "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "360", "title": "Drugs and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "406", "title": "Research Methods 2",                   "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "418", "title": "Language Development",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "433", "title": "Computational Cognitive Science",      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "441", "title": "Sensory Neuroscience",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "460", "title": "Cognitive Neuroscience",               "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  {
    "program_key": "psychology_honours_bsc",
    "name": "Psychology Honours (B.Sc.) (60 credits)",
    "program_type": "honours",
    "faculty": "Faculty of Science",
    "total_credits": 60,
    "description": "For students with high aptitude planning graduate study in psychology or neuroscience. Includes a research thesis.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/psychology/psychology-honours-bsc/",
    "blocks": [
      {
        "block_key": "psyc_hon_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 37,
        "courses_needed": None,
        "group_name": None,
        "notes": "PSYC 100 is a prerequisite, not credited within the 60-credit program.",
        "sort_order": 1,
        "courses": [
          {"subject": "PSYC", "catalog": "211", "title": "Introductory Behavioural Neuroscience","credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "212", "title": "Perception",                           "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "213", "title": "Cognition",                            "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "215", "title": "Social Psychology",                    "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "305", "title": "Statistics for Experimental Design",   "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "306", "title": "Research Methods in Psychology",       "credits": 3, "is_required": True},
          {"subject": "PSYC", "catalog": "380D1", "title": "Honours Research Project Seminar 1", "credits": 4.5, "is_required": True},
          {"subject": "PSYC", "catalog": "380D2", "title": "Honours Research Project Seminar 2", "credits": 4.5, "is_required": True},
          {"subject": "PSYC", "catalog": "439", "title": "Correlational Techniques",             "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "psyc_hon_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 23,
        "courses_needed": None,
        "group_name": None,
        "notes": "23 credits from PSYC 300+. At least 12 credits from PSYC 400+.",
        "sort_order": 2,
        "courses": [
          {"subject": "PSYC", "catalog": "302", "title": "Physiological Psychology",             "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "308", "title": "Motivation",                           "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "336", "title": "Language and the Brain",               "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "350", "title": "Developmental Cognitive Neuroscience", "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "360", "title": "Drugs and Behaviour",                  "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "418", "title": "Language Development",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "433", "title": "Computational Cognitive Science",      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "441", "title": "Sensory Neuroscience",                 "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "460", "title": "Cognitive Neuroscience",               "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  EARTH & PLANETARY SCIENCES
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "earth_planetary_sciences_major_bsc",
    "name": "Earth and Planetary Sciences Major (B.Sc.) (63 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 63,
    "description": "Covers the solid Earth, oceans, atmosphere, and solar system through geology, geochemistry, geophysics, and remote sensing.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/earth-planetary-sciences/earth-planetary-sciences-major-bsc/",
    "blocks": [
      {
        "block_key": "epsc_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 45,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "EPSC", "catalog": "201", "title": "Understanding Planet Earth",           "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "202", "title": "The Fluid Earth",                      "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "203", "title": "Earth and Life",                       "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "210", "title": "Earth Processes",                      "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "220", "title": "Earth Materials",                      "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "230", "title": "Geological Maps and Structures",       "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "321", "title": "Geomorphology and Surficial Processes","credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "330", "title": "Igneous and Metamorphic Petrology",    "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "331", "title": "Sedimentology and Stratigraphy",       "credits": 3, "is_required": True},
          {"subject": "EPSC", "catalog": "332", "title": "Structural Geology",                   "credits": 3, "is_required": True},
          {"subject": "CHEM", "catalog": "110", "title": "General Chemistry 1",                  "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "101", "title": "Introductory Physics – Mechanics",     "credits": 3, "is_required": True},
          {"subject": "PHYS", "catalog": "102", "title": "Introductory Physics – Electromagnetism","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "139", "title": "Calculus (Science Program)",           "credits": 4, "is_required": True},
          {"subject": "MATH", "catalog": "133", "title": "Vectors, Matrices and Geometry",       "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "epsc_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 18,
        "courses_needed": None,
        "group_name": None,
        "notes": "18 credits from EPSC 300+.",
        "sort_order": 2,
        "courses": [
          {"subject": "EPSC", "catalog": "401", "title": "Geophysics",                           "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "404", "title": "Geochemistry",                         "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "407", "title": "Plate Tectonics and the Continental Crust","credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "410", "title": "Mineralogy",                           "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "420", "title": "Ore Deposits",                         "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "440", "title": "Paleontology",                         "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "449", "title": "Planetary Geoscience",                 "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "455", "title": "Glaciology",                           "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "219", "title": "Meteorology",                          "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "305", "title": "Ocean and Atmosphere Dynamics 1",      "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  ATMOSPHERIC & OCEANIC SCIENCES
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "atmospheric_sciences_major_bsc",
    "name": "Atmospheric Science Major (B.Sc.) (62 credits)",
    "program_type": "major",
    "faculty": "Faculty of Science",
    "total_credits": 62,
    "description": "Covers meteorology, climatology, atmospheric dynamics, thermodynamics, and remote sensing.",
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/atmospheric-oceanic-sciences/atmospheric-science-major-bsc/",
    "blocks": [
      {
        "block_key": "atoc_major_req",
        "title": "Required Courses",
        "block_type": "required",
        "credits_needed": 24,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "ATOC", "catalog": "214", "title": "Introduction: Physics of the Atmosphere","credits": 3, "is_required": True},
          {"subject": "ATOC", "catalog": "312", "title": "Rotating Fluid Dynamics",               "credits": 3, "is_required": True},
          {"subject": "ATOC", "catalog": "315", "title": "Thermodynamics and Convection",         "credits": 3, "is_required": True},
          {"subject": "COMP", "catalog": "208", "title": "Computer Programming for Physical Sciences and Engineering","credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "222", "title": "Calculus 3",                            "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "223", "title": "Linear Algebra",                        "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "314", "title": "Advanced Calculus",                     "credits": 3, "is_required": True},
          {"subject": "MATH", "catalog": "315", "title": "Ordinary Differential Equations",       "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "atoc_major_comp",
        "title": "Complementary Courses",
        "block_type": "choose_credits",
        "credits_needed": 38,
        "courses_needed": None,
        "group_name": None,
        "notes": "38 credits from approved ATOC, EPSC, PHYS streams and complementary courses.",
        "sort_order": 2,
        "courses": [
          {"subject": "ATOC", "catalog": "215", "title": "Introduction to Oceanography",          "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "219", "title": "Meteorology",                           "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "305", "title": "Ocean and Atmosphere Dynamics 1",       "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "306", "title": "Ocean and Atmosphere Dynamics 2",       "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "401", "title": "Atmospheric Thermodynamics",            "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "404", "title": "Climate Dynamics",                      "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "408", "title": "Mesoscale Meteorology",                 "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "420", "title": "Remote Sensing of Environment",         "credits": 3, "is_required": False},
          {"subject": "ATOC", "catalog": "430", "title": "Climate Change Science",                "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "202", "title": "The Fluid Earth",                       "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "321", "title": "Geomorphology and Surficial Processes", "credits": 3, "is_required": False},
          {"subject": "EPSC", "catalog": "455", "title": "Glaciology",                            "credits": 3, "is_required": False},
          {"subject": "PHYS", "catalog": "230", "title": "Dynamics of Simple Systems",            "credits": 3, "is_required": False},
          {"subject": "PHYS", "catalog": "232", "title": "Heat and Waves",                        "credits": 3, "is_required": False},
        ],
      },
    ],
  },

  # ══════════════════════════════════════════════════════════════════════
  #  COGNITIVE SCIENCE
  # ══════════════════════════════════════════════════════════════════════
  {
    "program_key": "cognitive_science_minor_bsc",
    "name": "Cognitive Science Minor (B.Sc.) (24 credits)",
    "program_type": "minor",
    "faculty": "Faculty of Science",
    "total_credits": 24,
    "description": (
      "Interdisciplinary minor drawn from computer science/mathematics, linguistics, philosophy, "
      "and psychology. Students take a core course plus 9 credits from each of 2 of 4 areas."
    ),
    "ecalendar_url": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/programs/cognitive-science/cognitive-science-minor-bsc/",
    "blocks": [
      {
        "block_key": "cogsci_req",
        "title": "Required Core",
        "block_type": "required",
        "credits_needed": 3,
        "courses_needed": None,
        "group_name": None,
        "notes": None,
        "sort_order": 1,
        "courses": [
          {"subject": "PSYC", "catalog": "433", "title": "Computational Cognitive Science", "credits": 3, "is_required": True},
        ],
      },
      {
        "block_key": "cogsci_cs_math",
        "title": "Area A – Computer Science & Mathematics",
        "block_type": "group",
        "credits_needed": 9,
        "courses_needed": None,
        "group_name": "Area A: Computer Science & Mathematics",
        "notes": "Choose 9 credits from this area or Area B, C, D (2 areas required).",
        "sort_order": 2,
        "courses": [
          {"subject": "COMP", "catalog": "206", "title": "Introduction to Software Systems",          "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "251", "title": "Algorithms and Data Structures",            "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "302", "title": "Programming Languages and Paradigms",       "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "307", "title": "Introduction to Web Development",           "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "330", "title": "Theory of Computation",                     "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "360", "title": "Algorithm Design",                          "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "424", "title": "Artificial Intelligence",                   "credits": 3, "is_required": False},
          {"subject": "COMP", "catalog": "551", "title": "Applied Machine Learning",                  "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "323", "title": "Probability",                               "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "324", "title": "Statistics",                                "credits": 3, "is_required": False},
          {"subject": "MATH", "catalog": "340", "title": "Discrete Mathematics",                      "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogsci_linguistics",
        "title": "Area B – Linguistics",
        "block_type": "group",
        "credits_needed": 9,
        "courses_needed": None,
        "group_name": "Area B: Linguistics",
        "notes": "Choose 9 credits from this area or Area A, C, D (2 areas required).",
        "sort_order": 3,
        "courses": [
          {"subject": "LING", "catalog": "201", "title": "Introduction to Linguistics",               "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "210", "title": "Phonetics",                                 "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "260", "title": "Syntax 1",                                  "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "320", "title": "Phonology 1",                               "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "330", "title": "Syntax 2",                                  "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "360", "title": "Semantics",                                 "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "371", "title": "Computational Linguistics",                 "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "440", "title": "Psycholinguistics",                         "credits": 3, "is_required": False},
          {"subject": "LING", "catalog": "460", "title": "Formal Syntax",                             "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogsci_philosophy",
        "title": "Area C – Philosophy",
        "block_type": "group",
        "credits_needed": 9,
        "courses_needed": None,
        "group_name": "Area C: Philosophy",
        "notes": "Choose 9 credits from this area or Area A, B, D (2 areas required).",
        "sort_order": 4,
        "courses": [
          {"subject": "PHIL", "catalog": "210", "title": "Introduction to Logic",                     "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "310", "title": "Philosophy of Mind",                        "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "340", "title": "Philosophy of Language",                    "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "355", "title": "Epistemology",                              "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "360", "title": "Advanced Logic",                            "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "415", "title": "Philosophy of Cognitive Science",           "credits": 3, "is_required": False},
          {"subject": "PHIL", "catalog": "444", "title": "Minds, Machines and Knowledge",             "credits": 3, "is_required": False},
        ],
      },
      {
        "block_key": "cogsci_psychology",
        "title": "Area D – Psychology",
        "block_type": "group",
        "credits_needed": 9,
        "courses_needed": None,
        "group_name": "Area D: Psychology",
        "notes": "Choose 9 credits from this area or Area A, B, C (2 areas required).",
        "sort_order": 5,
        "courses": [
          {"subject": "PSYC", "catalog": "212", "title": "Introduction to Cognitive Psychology",      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "260", "title": "Introduction to Brain and Behaviour",       "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "304", "title": "Brain and Behaviour",                       "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "305", "title": "Research Methods",                          "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "336", "title": "Language and the Brain",                    "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "341", "title": "Perceptual Processes",                      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "350", "title": "Developmental Cognitive Neuroscience",      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "418", "title": "Language Development",                      "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "440", "title": "Cognitive Neuroscience",                    "credits": 3, "is_required": False},
          {"subject": "PSYC", "catalog": "460", "title": "Perception and Action",                     "credits": 3, "is_required": False},
        ],
      },
    ],
  },

]  # END SCIENCE_PROGRAMS_PART3
