import { createContext, useContext, useState, useCallback } from 'react'

const LanguageContext = createContext(null)

const translations = {
  en: {
    // ── Sidebar Nav ───────────────────────────────────────
    'nav.chat': 'Academic Brief',
    'nav.courses': 'Courses',
    'nav.saved': 'Saved',
    'nav.calendar': 'Calendar',
    'nav.forum': 'Forum',
    'nav.profile': 'Profile',
    'nav.degreePlanning': 'Degree Planning',

    // ── Sidebar Footer / Popup ────────────────────────────
    'sidebar.settings': 'Settings',
    'sidebar.changeLanguage': 'Change Language',
    'sidebar.colorTheme': 'Color Theme',
    'sidebar.logOut': 'Log Out',
    'sidebar.signOut': 'Sign Out',

    // ── Settings Section Titles ───────────────────────────
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your McGill Advisor experience',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.privacyData': 'Privacy & Data',
    'settings.preferences': 'Preferences',

    // ── Settings Labels ───────────────────────────────────
    'settings.theme': 'Theme',
    'settings.themeDescription': 'Choose your preferred color scheme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.auto': 'Auto',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive updates via email',
    'settings.deadlineReminders': 'Deadline Reminders',
    'settings.deadlineRemindersDesc': 'Get notified about upcoming deadlines',
    'settings.courseUpdates': 'Course Updates',
    'settings.courseUpdatesDesc': 'Notifications about course changes',
    'settings.calendarNotifications': 'Calendar Notification Defaults',
    'settings.notifMethod': 'Default notification method',
    'settings.notifMethodDesc': 'How you want to be reminded by default',
    'settings.notifEmail': 'Email',
    'settings.notifSMS': 'Text (SMS)',
    'settings.notifBoth': 'Both',
    'settings.notifNone': 'None',
    'settings.notifEmailAddr': 'Notification email',
    'settings.notifEmailAddrDesc': 'Email address for calendar reminders',
    'settings.notifPhone': 'Phone number',
    'settings.notifPhoneDesc': 'Phone number for SMS reminders',
    'settings.notifTiming': 'Default reminder timing',
    'settings.notifTimingDesc': 'When to send reminders by default',
    'settings.notifSameDay': 'Same day',
    'settings.notifOneDay': '1 day before',
    'settings.notifOneWeek': '1 week before',
    'settings.notifEventTypes': 'Notify me about',
    'settings.notifEventTypesDesc': 'Which event types to receive reminders for',
    'settings.notifSave': 'Save Notification Preferences',
    'settings.notifSaved': 'Saved!',
    'settings.profileVisibility': 'Profile Visibility',
    'settings.profileVisibilityDesc': 'Who can see your profile',
    'settings.private': 'Private',
    'settings.friendsOnly': 'Friends Only',
    'settings.public': 'Public',
    'settings.shareProgress': 'Share Academic Progress',
    'settings.shareProgressDesc': 'Allow others to view your progress',
    'settings.language': 'Language',
    'settings.languageDesc': 'Interface language',
    'settings.timezone': 'Timezone',
    'settings.timezoneDesc': 'Your local timezone',

    // ── Danger zone ─────────────────────────────────────
    'settings.dangerZone': 'Danger Zone',
    'settings.deleteAccount': 'Delete Account',
    'settings.deleteAccountDesc': 'Permanently delete your account and all associated data. This cannot be undone.',
    'settings.deleteAccountBtn': 'Delete Account',
    'settings.deleteConfirmTitle': 'Delete your account?',
    'settings.deleteConfirmText': 'This will permanently delete your account, all your courses, grades, calendar events, and preferences. This action cannot be undone.',
    'settings.deleteConfirmPrompt': 'Type DELETE to confirm:',
    'settings.deleteConfirmPlaceholder': 'Type DELETE',
    'settings.deleteConfirmBtn': 'Permanently Delete',
    'settings.deleteDeleting': 'Deleting…',
    'settings.deleteError': 'Failed to delete account. Please try again.',
    'settings.exportData': 'Export Data',
    'settings.exportYourData': 'Export Your Data',
    'settings.exportDataDesc': 'Download all your data as JSON',
    'settings.exportModalText': 'This will download all your profile data, courses, and settings as a JSON file. You can use this for backup or to transfer your data.',
    'settings.downloadJson': 'Download JSON',
    'settings.dataExported': 'Data exported successfully!',

    // ── Profile Labels ────────────────────────────────────
    'profile.personalInfo': 'Personal Information',
    'profile.manageDetails': 'Manage your profile details',
    'profile.username': 'Username',
    'profile.email': 'Email Address',
    'profile.faculty': 'Faculty',
    'profile.major': 'Primary Major',
    'profile.additionalMajors': 'Additional Majors',
    'profile.minor': 'Minor',
    'profile.primaryMinor': 'Primary Minor',
    'profile.additionalMinors': 'Additional Minors',
    'profile.concentration': 'Concentration',
    'profile.year': 'Academic Year',
    'profile.gpa': 'GPA',
    'profile.currentGpa': 'Current GPA',
    'profile.editProfile': 'Edit Profile',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.changePhoto': 'Change Photo',
    'profile.notSpecified': 'Not specified',
    'profile.notSet': 'Not set',
    'profile.completeness': 'Profile Completeness',
    'profile.academicInfo': 'Academic Information',
    'profile.contactInfo': 'Contact Information',
    'profile.additionalInfo': 'Additional Information',
    'profile.academicInterests': 'Academic Interests',
    'profile.noInterests': 'No interests added yet. Add your academic interests to get personalized recommendations!',

    // ── Profile Tab Sections ──────────────────────────────
    'profile.academicPerformance': 'Academic Performance',
    'profile.gpaTip': 'Keep your GPA updated for better course recommendations',
    'profile.degreeProgress': 'Degree Progress',
    'profile.interestsPreferences': 'Interests & Preferences',
    'profile.achievements': 'Achievements',
    'profile.personalizedInsights': 'Personalized Insights',
    'profile.insightsSubtitle': 'Recommendations based on your profile and activity',
    'profile.insightsEmpty': 'Complete your profile and interact with the AI advisor to get personalized recommendations!',
    'profile.signOutTitle': 'Sign Out',
    'profile.signOutDescription': 'Sign out of your McGill AI Advisor account',
    'profile.mcgillStudent': 'McGill Student',
    'profile.yearNotSet': 'Year not set',
    'profile.yearLabel': 'Year {year}',

    // ── Profile Form ──────────────────────────────────────
    'profileForm.basicInfo': 'Basic Information',
    'profileForm.enterUsername': 'Enter Username',
    'profileForm.optional': 'Optional',
    'profileForm.displayName': 'Your display name',
    'profileForm.academicInfo': 'Academic Information',
    'profileForm.academicInfoDesc': 'Your faculty, program, and year of study',
    'profileForm.selectFaculty': 'Select your faculty',
    'profileForm.selectYear': 'Select year',
    'profileForm.selectMajor': 'Select your major',
    'profileForm.selectMinor': 'Select a minor (optional)',
    'profileForm.performanceInterests': 'Performance & Interests',
    'profileForm.performanceInterestsDesc': 'Help us personalize your experience',
    'profileForm.gpaScale': 'Scale of 0.0 - 4.0',
    'profileForm.separateCommas': 'Separate with commas',
    'profileForm.advancedStanding': 'Advanced Standing',
    'profileForm.advancedStandingDesc': 'AP, IB, or transfer credits',
    'profileForm.courseCode': 'Course Code',
    'profileForm.credits': 'Credits',
    'profileForm.addCourse': 'Add Course',
    'profileForm.removeCourse': 'Remove',
    'profileForm.forDoubleMajors': 'For double/joint majors',
    'profileForm.multipleMinors': 'If you have multiple minors',
    'profileForm.verified': 'Verified',
    'profileForm.completeBetterRecs': 'Complete your profile to get better course recommendations',
    'profileForm.noInterestsAdded': 'No interests added',

    // ── Common ────────────────────────────────────────────
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.saveChanges': 'Save Changes',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.areYouSure': 'Are you sure?',
    'common.cancel': 'Cancel',
    'common.calculator': 'Calculator',
    'common.english': 'English',
    'common.french': 'Français',
    'common.user': 'User',
    'common.na': 'N/A',
    'common.reloadPage': 'Reload Page',

    // ── Chat ──────────────────────────────────────────────
    'chat.placeholder': 'Ask me anything about courses, planning, or McGill academics...',
    'chat.send': 'Send',
    'chat.sending': 'Sending...',
    'chat.newChat': 'New Chat',
    'chat.chatSession': 'Chat Session',
    'chat.chatHistory': 'Chat History',
    'chat.noPreviousChats': 'No previous chats',
    'chat.loadingHistory': 'Loading chat history...',
    'chat.failedToSend': 'Failed to send message. Please try again.',
    'chat.failedToLoad': 'Failed to load chat history',
    'chat.dropFiles': 'Drop files here to attach',
    'chat.dropFilesSubtext': 'PDF, Images, Text files (max 32MB)',
    'chat.welcomeMessage': 'Hello! I\'m your McGill AI Academic Advisor. How can I help you plan your courses today?',
    'chat.errorSending': 'Failed to send message. Please try again.',
    'chat.historyTitle': 'Chat History',
    'chat.showHistory': 'Show chat history',
    'chat.closeHistory': 'Close history',

    // ── Badges ────────────────────────────────────────────
    'badges.unlocked': '{count} of {total} unlocked',
    'badges.gettingStarted': 'Getting Started',
    'badges.gettingStartedDesc': 'Set up your profile',
    'badges.courseExplorer': 'Course Explorer',
    'badges.courseExplorerDesc': 'Saved 10+ courses',
    'badges.chatMaster': 'Chat Master',
    'badges.chatMasterDesc': '50+ AI conversations',
    'badges.wellRounded': 'Well-Rounded',
    'badges.wellRoundedDesc': 'Took courses in 5+ departments',
    'badges.deansList': 'Dean\'s List',
    'badges.deansListDesc': 'GPA above 3.7',
    'badges.earlyBird': 'Early Bird',
    'badges.earlyBirdDesc': 'Plan next semester early',
    'badges.mcgillVeteran': 'McGill Veteran',
    'badges.mcgillVeteranDesc': 'Complete 60+ credits',
    'badges.scholar': 'Scholar',
    'badges.scholarDesc': 'Complete 90+ credits',
    'badges.almostThere': 'Almost There!',
    'badges.almostThereDesc': 'Complete 100+ credits',

    // ── Insights ──────────────────────────────────────────
    'insights.basedOnInterests': 'Based on your interests',
    'insights.exploreCourses': 'Explore courses in {interests}',
    'insights.peersAlsoTook': 'Students in your major also took',
    'insights.frequentlyAsk': 'You frequently ask about',
    'insights.outstandingPerformance': 'Outstanding Performance',
    'insights.honoursProgramsQualify': 'Your GPA qualifies you for honours programs and competitive opportunities',
    'insights.almostThere': 'Almost there!',
    'insights.creditsUntilGrad': 'Only {count} credits until graduation',

    // ── Courses ───────────────────────────────────────────
    'courses.searchPlaceholder': 'Search for courses (e.g., COMP202, Introduction to Programming)...',
    'courses.searching': 'Searching...',
    'courses.filters': 'Filters',
    'courses.sortBy': 'Sort by:',
    'courses.relevance': 'Relevance',
    'courses.addToSaved': 'Add to favorites',
    'courses.removeFromSaved': 'Remove from favorites',
    'courses.markCompleted': 'Mark as completed',
    'courses.markNotCompleted': 'Mark as not completed',
    'courses.courseDetails': 'Course Details',
    'courses.prerequisites': 'Prerequisites',
    'courses.credits': 'Credits',
    'courses.sections': 'Sections',
    'courses.instructor': 'Instructor',
    'courses.rating': 'Rating',
    'courses.difficulty': 'Difficulty',
    'courses.reviews': 'Reviews',
    'courses.wouldRetake': 'Would Retake',
    'courses.loadingDetails': 'Loading course details...',
    'courses.noResults': 'No courses found matching your search.',
    'courses.failedSearch': 'Failed to search courses. Please try again.',
    'courses.failedDetails': 'Failed to load course details.',
    'courses.explorerTitle': 'Course Explorer with Professor Ratings',
    'courses.explorerDesc': 'Search through McGill courses with historical grade data and live RateMyProfessor ratings.',
    'courses.failedUpdate': 'Failed to update favorites',
    'courses.failedCompleted': 'Failed to update completed courses',
    'courses.failedMarkCompleted': 'Failed to mark course as completed',
    'courses.foundResults': 'Found {count} course',
    'courses.foundResultsPlural': 'Found {count} courses',
    'courses.sectionsAvailable': '{count} section available',
    'courses.sectionsAvailablePlural': '{count} sections available',
    'courses.newSearch': 'New Search',
    'courses.backToResults': 'Back to Results',
    'courses.average': 'Average',
    'courses.professorRating': 'Professor Rating',
    'courses.search': 'Search',
    'courses.sortRatingHigh': '⭐ Rating (High to Low)',
    'courses.sortRatingLow': '⭐ Rating (Low to High)',
    'courses.sortNameAZ': '📚 Course Name (A-Z)',
    'courses.sortNameZA': '📚 Course Name (Z-A)',
    'courses.sortInstructorAZ': '👤 Professor (A-Z)',
    'courses.sortInstructorZA': '👤 Professor (Z-A)',
    'courses.vsbLabel': 'Visual Schedule Builder',
    'courses.vsbDesc': 'Plan your timetable on McGill\'s official schedule builder',

    // ── Study Abroad ───────────────────────────────────────
    'sa.title': 'Study Abroad & Field Studies',
    'sa.subtitle': 'Exchanges, field semesters, internships, and study away — credits count toward your McGill degree.',
    'sa.browse': 'Browse',
    'sa.saved': 'Saved',
    'sa.statPartners': 'partner universities',
    'sa.statCountries': 'countries',
    'sa.statTypes': 'program types',
    'sa.searchPlaceholder': 'Search programs, destinations…',
    'sa.programs': '{count} programs',
    'sa.program': '{count} program',
    'sa.matchingFilters': ' matching filters',
    'sa.clearFilters': 'Clear filters',
    'sa.noMatch': 'No programs match your filters.',
    'sa.noSaved': 'No saved programs yet.',
    'sa.noSavedSub': 'Browse programs and click the bookmark to save them here.',
    'sa.footerText': 'Looking for something not listed here?',
    'sa.footerLink': 'Visit McGill Abroad',
    'sa.eligibility': 'Eligibility',
    'sa.deadlines': 'Deadlines',
    'sa.saveBookmark': 'Save',
    'sa.removeBookmark': 'Remove bookmark',
    'sa.typeAll': 'All',
    'sa.typeExchange': 'Exchange',
    'sa.typeField': 'Field Studies',
    'sa.typeCourses': 'Courses Abroad',
    'sa.typeInternship': 'Internship / Co-op',
    'sa.typeIut': 'IUT / Study Away',
    'sa.regionAll': 'All Regions',
    'sa.regionEurope': 'Europe',
    'sa.regionAmericas': 'Americas',
    'sa.regionAsia': 'Asia-Pacific',
    'sa.regionAfrica': 'Africa & Middle East',
    'sa.regionCanada': 'Canada',
    'sa.badgeExchange': 'Exchange',
    'sa.badgeField': 'Field Study',
    'sa.badgeCourses': 'Courses Abroad',
    'sa.badgeInternship': 'Internship',
    'sa.badgeIut': 'IUT / Study Away',

    // ── Feedback ───────────────────────────────────────────
    'fb.button': 'Feedback',
    'fb.title': 'Send Feedback',
    'fb.modePrompt': 'What would you like to tell us?',
    'fb.modeGeneral': 'General Feedback',
    'fb.modeGeneralSub': 'Bug reports, suggestions, anything else',
    'fb.modeMissing': 'Missing Course',
    'fb.modeMissingSub': 'Can\'t find a course you\'re looking for?',
    'fb.generalDesc': 'Tell us what\'s working, what\'s broken, or what you\'d like to see.',
    'fb.generalPlaceholder': 'Your feedback...',
    'fb.missingDesc': 'Tell us which course you couldn\'t find and we\'ll work on adding it.',
    'fb.missingPlaceholder': 'Course code, e.g. POLS 340',
    'fb.missingExtra': 'Any extra context? (optional)',
    'fb.back': '← Back',
    'fb.send': 'Send',
    'fb.sending': 'Sending…',
    'fb.submit': 'Submit',
    'fb.success': 'Thanks! We got your feedback.',
    'fb.duplicate': 'Looks like you already submitted this recently.',
    'fb.close': 'Close',

    // ── Clubs ──────────────────────────────────────────────
    'clubs.title': 'Student Clubs',
    'clubs.subtitle': 'Discover, join, and sync McGill clubs to your calendar',
    'clubs.submitBtn': 'Submit a Club',
    'clubs.tabExplore': 'Explore',
    'clubs.tabMine': 'My Clubs',
    'clubs.searchPlaceholder': 'Search clubs by name, keyword, or category…',
    'clubs.sortDefault': 'Default order',
    'clubs.sortMembers': 'Most members',
    'clubs.sortName': 'Name A→Z',
    'clubs.filterAll': 'All',
    'clubs.loading': 'Loading clubs…',
    'clubs.loadingMine': 'Loading your clubs…',
    'clubs.noResults': 'No clubs found',
    'clubs.noResultsHint': 'Try different keywords or',
    'clubs.noResultsSubmit': 'submit a new club',
    'clubs.results': '{count} clubs',
    'clubs.result': '{count} club',
    'clubs.inCategory': ' in',
    'clubs.matching': ' matching',
    'clubs.showingFirst': ' — showing first {count}',
    'clubs.loadMore': 'Load more clubs',
    'clubs.loadingMore': 'Loading…',
    'clubs.noJoined': 'No clubs joined yet',
    'clubs.noJoinedHint': "Find something you're passionate about in the Explore tab.",
    'clubs.browseBtn': 'Browse Clubs',
    'clubs.joinedToast': 'Joined {name}!',
    'clubs.back': 'Back',
    'clubs.leaveClub': 'Leave Club',
    'clubs.joinClub': 'Join Club',
    'clubs.members': 'Members',
    'clubs.meets': 'Meets',
    'clubs.location': 'Location',
    'clubs.about': 'About',
    'clubs.calendarSync': 'Calendar Sync',
    'clubs.calSyncDesc': "Sync this club's meetings to your Calendar tab.",
    'clubs.synced': 'Synced',
    'clubs.notSynced': 'Not synced',
    'clubs.linksContact': 'Links & Contact',
    'clubs.visitWebsite': 'Visit Website',
    'clubs.joinedBadge': 'Joined',
    'clubs.calOn': 'Calendar On',
    'clubs.calOff': 'Calendar Off',
    'clubs.leave': 'Leave',
    'clubs.joinedBtn': 'Joined!',
    'clubs.joinBtn': 'Join',
    'clubs.syncBtn': 'Sync',
    'clubs.submitModalTitle': 'Submit a Club',
    'clubs.submitModalSub': "Help grow McGill's club directory",
    'clubs.submitSuccess': 'Submitted!',
    'clubs.submitSuccessDesc': 'Your club has been queued for review and will be added soon.',
    'clubs.done': 'Done',
    'clubs.fieldName': 'Club Name',
    'clubs.fieldNamePlaceholder': 'e.g. McGill Chess Club',
    'clubs.fieldCategory': 'Category',
    'clubs.fieldCategoryDefault': 'Select…',
    'clubs.fieldLocation': 'Location',
    'clubs.fieldLocationPlaceholder': 'e.g. Burnside 105',
    'clubs.fieldDesc': 'Description',
    'clubs.fieldDescPlaceholder': 'What does this club do?',
    'clubs.fieldSchedule': 'Meeting Schedule',
    'clubs.fieldSchedulePlaceholder': 'Tuesdays 5–7pm',
    'clubs.fieldEmail': 'Contact Email',
    'clubs.fieldUrl': 'Website URL',
    'clubs.cancel': 'Cancel',
    'clubs.submitting': 'Submitting…',
    'clubs.submitClub': 'Submit Club',
    'clubs.required': 'Required',
    'clubs.catAcademic': 'Academic',
    'clubs.catEngineering': 'Engineering & Technology',
    'clubs.catProfessional': 'Professional',
    'clubs.catDebate': 'Debate & Politics',
    'clubs.catAthletics': 'Athletics & Recreation',
    'clubs.catArts': 'Arts & Culture',
    'clubs.catEnvironment': 'Environment',
    'clubs.catHealth': 'Health & Wellness',
    'clubs.catCommunity': 'Community Service',
    'clubs.catInternational': 'International',
    'clubs.catScience': 'Science',
    'clubs.catSocial': 'Social',
    'clubs.catSpiritual': 'Spiritual & Religious',

    // ── Auth / Login ────────────────────────────────────────
    'auth.brandHeadline': 'Your AI academic advisor.',
    'auth.brandSub': 'Personalized course planning, historical grade data, and intelligent guidance — all in one place.',
    'auth.feature1': 'AI-powered course recommendations',
    'auth.feature2': 'Historical grade data across 10,000+ sections',
    'auth.feature3': 'Degree planning tailored to your major & goals',
    'auth.feature4': '24/7 academic support via chat',
    'auth.tabSignIn': 'Sign In',
    'auth.tabCreate': 'Create Account',
    'auth.titleForgot': 'Reset password',
    'auth.titleLogin': 'Welcome back',
    'auth.titleSignup': 'Get started',
    'auth.subForgot': "We'll send a reset link to your email.",
    'auth.subLogin': 'Sign in to continue your academic journey.',
    'auth.subSignup': 'Create your free Symbolos account.',
    'auth.labelUsername': 'Username',
    'auth.labelEmail': 'Email Address',
    'auth.labelPassword': 'Password',
    'auth.forgotLink': 'Forgot password?',
    'auth.showPassword': 'Show password',
    'auth.hidePassword': 'Hide password',
    'auth.passwordHint': 'At least 8 characters with uppercase, lowercase, and numbers',
    'auth.strengthWeak': 'Weak',
    'auth.strengthFair': 'Fair',
    'auth.strengthGood': 'Good',
    'auth.strengthStrong': 'Strong',
    'auth.btnForgot': 'Send Reset Link',
    'auth.btnLogin': 'Sign In',
    'auth.btnSignup': 'Create Account',
    'auth.loadingForgot': 'Sending...',
    'auth.loadingLogin': 'Signing in...',
    'auth.loadingSignup': 'Creating account...',
    'auth.backToLogin': '← Back to Sign In',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUpLink': 'Sign Up',
    'auth.signInLink': 'Sign In',
    'auth.resetSent': 'If an account exists with this email, a reset link has been sent.',
    'auth.accountCreated': 'Account created! Redirecting...',
    'auth.genericError': 'Something went wrong. Please try again.',
    'auth.langToggle': 'Français',

    // ── Onboarding / ProfileSetup ───────────────────────
    'ps.txTitle': 'Import your transcript',
    'ps.txSubtitle': "We'll automatically pull your courses, grades, GPA, and program info.",
    'ps.stepTranscript': 'Transcript',
    'ps.stepSyllabi': 'Syllabi',
    'ps.dropTranscript': 'Drop your unofficial transcript here',
    'ps.dropBrowse': 'or click to browse · PDF only · max 10 MB',
    'ps.importTranscript': 'Import Transcript',
    'ps.skipForNow': 'Skip for now',
    'ps.hintTranscript': 'You can also do this later from the <strong>Profile tab</strong> — find <strong>Import Transcript</strong> in the Degree Progress card.',
    'ps.txUploading': 'Importing your transcript…',
    'ps.txUploadingSub': 'Claude is reading your courses, grades, and program info.',
    'ps.txDone': 'Transcript imported!',
    'ps.txDoneSub': 'Your academic history is ready. Next, upload your syllabi.',
    'ps.txCompletedLabel': 'completed courses',
    'ps.txCurrentLabel': 'current courses',
    'ps.txProfileUpdated': 'profile updated',
    'ps.continueSyllabi': 'Continue to Syllabi',
    'ps.txError': 'Import failed',
    'ps.tryAgain': 'Try Again',
    'ps.skipSyllabi': 'Skip to Syllabi',
    'ps.txPdfOnly': 'Please upload a PDF file.',
    'ps.txTooLarge': 'File must be under 10 MB.',
    'ps.sylTitle': 'Upload your syllabi',
    'ps.sylSubtitle': "We'll extract schedules, exams, and professor info — and fill in your calendar automatically.",
    'ps.sylInfo1': 'Lecture times & rooms added to your calendar',
    'ps.sylInfo2': 'Professor, office hours & contact info',
    'ps.sylInfo3': 'Exams & assignment deadlines with reminders',
    'ps.dropSyllabi': 'Drop syllabus PDFs here',
    'ps.dropSyllabiSub': 'Upload all at once · PDF only · max 15 MB each',
    'ps.addMore': 'Add more',
    'ps.importSyllabi': 'Import Syllabi',
    'ps.importSyllabusCount': 'Import {count} Syllabus',
    'ps.importSyllabiCount': 'Import {count} Syllabi',
    'ps.sylUploading': 'Processing your syllabi…',
    'ps.sylUploadingSub': 'Claude is reading course schedules, exams, and professor info from {count} file.',
    'ps.sylUploadingSubPlural': 'Claude is reading course schedules, exams, and professor info from {count} files.',
    'ps.sylDone': 'Syllabi imported!',
    'ps.sylDoneSub': 'Your calendar and course profiles have been updated.',
    'ps.sylEventsLabel': 'calendar events added',
    'ps.sylCoursesLabel': '{count} course enriched',
    'ps.sylCoursesLabelPlural': '{count} courses enriched',
    'ps.toDashboard': 'Go to Dashboard',
    'ps.hintSyllabi': 'You can upload syllabi anytime from the <strong>Calendar</strong> or <strong>Profile</strong> tab.',
    'ps.sylError': 'Import failed',
    'ps.skipDashboard': 'Skip to Dashboard',
    'ps.loading': 'Loading…',
    'ps.sylPdfOnly': 'Please upload PDF files only (max 15 MB each).',

    // ── Calendar ──────────────────────────────────────────
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.addEvent': 'Add Event',
    'calendar.announcements': 'Announcements',
    'calendar.exportBtn': 'Export',
    'calendar.exportICS': 'Download .ics file',
    'calendar.exportGoogleHelp': 'Import into Google Calendar',
    'calendar.addToGoogle': 'Add to Google Calendar',
    'calendar.academicDates': 'McGill Academic',
    'calendar.unionEvents': 'Student Union',
    'calendar.clubEvents': 'Club Event',
    'calendar.personalEvents': 'Personal',
    'calendar.remindersSet': 'Reminders scheduled!',
    'calendar.noUpcoming': 'No upcoming events.',
    'calendar.subtitle': 'Academic dates, events & reminders',
    'calendar.calendarView': 'Calendar',
    'calendar.addEventBtn': 'Add Event',
    'calendar.prevMonth': 'Previous month',
    'calendar.nextMonth': 'Next month',
    'calendar.todayBtn': 'Today',
    'calendar.eventTitle': 'Event Title',
    'calendar.eventTitlePlaceholder': 'e.g. Study Group, Club Meeting',
    'calendar.date': 'Date',
    'calendar.time': 'Time (optional)',
    'calendar.eventType': 'Event Type',
    'calendar.groupCategory': 'Group / Category (optional)',
    'calendar.groupPlaceholder': 'e.g. Math Club, SSMU',
    'calendar.description': 'Description (optional)',
    'calendar.descPlaceholder': 'Add details about this event…',
    'calendar.reminders': 'Reminders',
    'calendar.notifyVia': 'Notify me via',
    'calendar.email': 'Email',
    'calendar.sendingTo': 'Sending to',
    'calendar.sms': 'Text (SMS)',
    'calendar.emailAddress': 'Email address',
    'calendar.phoneNumber': 'Phone number',
    'calendar.whenToRemind': 'When to remind',
    'calendar.remind7Days': '7 days before',
    'calendar.remind1Day': '1 day before',
    'calendar.addEventTitle': 'Add New Event',
    'calendar.editEventTitle': 'Edit Event',
    'calendar.saveChanges': 'Save Changes',
    'calendar.cancel': 'Cancel',
    'calendar.delete': 'Delete',
    'calendar.editEvent': 'Edit Event',
    'calendar.reminderSet': 'Email reminder set (7 days & 1 day before)',
    'calendar.daysAgo': 'd ago',
    'calendar.today2': 'Today!',
    'calendar.inDays': 'in',
    'calendar.inDaysSuffix': 'd',
    'calendar.upcomingIn7': 'coming up in the next 7 days',
    'calendar.event': 'event',
    'calendar.events': 'events',
    'calendar.tomorrow': 'Tomorrow',
    'calendar.inXDays': 'In {n} days',
    'calendar.mcgillOfficial': 'McGill Official',
    'cal.moreDots': 'more',
    'calendar.remindSameDay': 'Same day',
    'calendar.notifOn': 'ON',
    'calendar.notifOff': 'OFF',
    'calendar.enableNotifications': 'Enable reminders for this event',

    // ── Right Sidebar / Website Assistant ─────────────────
    'rsb.pinnedChat': 'Pinned Chat',
    'rsb.unpinCard': 'Unpin card',
    'rsb.closeSidebar': 'Close sidebar',
    'rsb.noMessages': 'No messages yet. Ask a follow-up below to continue the conversation.',
    'rsb.websiteAssistant': 'Website Assistant',
    'rsb.askAnything': 'Ask me anything',
    'rsb.close': 'Close',
    'rsb.openPinned': 'Open pinned chat',
    'rsb.openAssistant': 'Open Website Assistant',
    'rsb.navPlaceholder': 'Ask me about courses, planning, or how to navigate…',
    'rsb.errorMsg': '❌ Something went wrong. Please try again.',
    'rsb.greeting': "Hi! I'm your academic advisor. You're on {tab} — ask me anything or tap a suggestion below.",
    'rsb.followUpPlaceholder': 'Ask a follow-up…',

    // Nav suggestion chips per tab
    'rsb.nav.courses.1': 'How do I search for a course?',
    'rsb.nav.courses.2': 'What do the GPA badges mean?',
    'rsb.nav.courses.3': 'How do I mark a course complete?',
    'rsb.nav.calendar.1': 'How do I add an event?',
    'rsb.nav.calendar.2': 'How do I upload a syllabus?',
    'rsb.nav.calendar.3': 'Where are my final exam dates?',
    'rsb.nav.degree.1': 'How does degree progress work?',
    'rsb.nav.degree.2': 'What is a complementary course?',
    'rsb.nav.degree.3': 'How do I add a minor?',
    'rsb.nav.profile.1': 'How do I upload my transcript?',
    'rsb.nav.profile.2': 'How do I add transfer credits?',
    'rsb.nav.profile.3': 'How do I change my major?',
    'rsb.nav.abroad.1': 'How do exchanges work at McGill?',
    'rsb.nav.abroad.2': 'Which programs are in Europe?',
    'rsb.nav.abroad.3': 'How do credits transfer?',
    'rsb.nav.default.1': 'What can you help me with?',
    'rsb.nav.default.2': 'How do I plan my degree?',
    'rsb.nav.default.3': 'Show me my course options',

    // Tab labels used in greeting
    'rsb.tab.courses': 'Courses',
    'rsb.tab.calendar': 'Calendar',
    'rsb.tab.degree': 'Degree Planning',
    'rsb.tab.profile': 'Profile',
    'rsb.tab.abroad': 'Study Abroad',
    'rsb.tab.default': 'the dashboard',

    // ── CoursesTab RMP labels ─────────────────────────────
    'courses.yourProf': '📄 Your prof',
    'courses.rmpLooking': 'Looking up RateMyProfessors…',
    'courses.rmpFind': 'Find {name} on RateMyProfessors →',
    'courses.rmpViewLink': 'View on RMP',

    // ── Calendar static event titles (EN) ─────────────────
    'cal.fallBegins': 'Fall Semester Begins',
    'cal.fallMidterms': 'Fall Midterm Season',
    'cal.winterMidterms': 'Winter Midterm Season',
    'cal.cancelRegistration': 'Deadline to Cancel Registration',
    'cal.withdrawalRefund': 'Course/University Withdrawal WITH Refund Deadline',
    'cal.easterMonday': 'Easter Monday (No Classes)',
    'cal.makeupDay': 'Makeup Lecture Day (Friday Schedule)',
    'cal.studyDay': 'Study Day (No Classes)',
    'cal.addDropFall': 'Add/Drop Deadline (Fall)',
    'cal.thanksgiving': 'Thanksgiving Day (No Classes)',
    'cal.fallReadingWeek': 'Fall Reading Week',
    'cal.withdrawalFall': 'Withdrawal Deadline (Fall)',
    'cal.lastDayFall': 'Last Day of Fall Classes',
    'cal.fallExamsBegin': 'Fall Exam Period Begins',
    'cal.fallExamsEnd': 'Fall Exam Period Ends',
    'cal.winterBegins': 'Winter Semester Begins',
    'cal.addDropWinter': 'Add/Drop Deadline (Winter)',
    'cal.winterReadingWeek': 'Winter Reading Week',
    'cal.withdrawalWinter': 'Withdrawal Deadline (Winter)',
    'cal.goodFriday': 'Good Friday (No Classes)',
    'cal.lastDayWinter': 'Last Day of Winter Classes',
    'cal.winterExamsBegin': 'Winter Exam Period Begins',
    'cal.winterExamsEnd': 'Winter Exam Period Ends',
    'cal.registration': 'Course Registration Opens',
    'cal.convocation': 'Convocation (Spring)',
    'cal.ssmuGA': 'SSMU General Assembly',
    'cal.froshWeek': 'Frosh Week Kickoff',
    'cal.hackathon': 'McGill Hack-a-thon 2025',
    'cal.careerFair': 'Engineering Career Fair',
    'cal.symposium': 'Arts & Science Symposium',
    'cal.foodFestival': 'International Food Festival',
    'cal.studyBreak': 'Finals Study Break Social',
    'cal.catSSMU': 'SSMU',
    'cal.catCSClub': 'CS Club',
    'cal.catEUS': 'EUS',
    'cal.catArts': 'Arts Council',
    'cal.descSSMUGA': 'Winter General Assembly — all students welcome.',
    'cal.descFrosh': 'Opening ceremony for Frosh Week 2025.',
    'cal.descHack': '24-hour hackathon open to all faculties.',
    'cal.descCareer': 'Annual Engineering Undergraduate Society career fair.',
    'cal.descSymp': 'Student research presentations.',
    'cal.descFood': 'Celebrate global cultures on campus.',
    'cal.descStudyBreak': 'Free snacks and stress relief before finals.',

    // ── Saved Courses ─────────────────────────────────────
    'saved.savedCourses': 'Saved Courses',
    'saved.completed': 'Completed',
    'saved.noSavedCourses': 'No Saved Courses Yet',
    'saved.noSavedCoursesDesc': 'Save courses from the Course Explorer to see them here',
    'saved.noCompletedCourses': 'No Completed Courses Yet',
    'saved.noCompletedCoursesDesc': 'Mark courses as completed to track your progress',

    // ── Degree Progress ───────────────────────────────────
    'degree.completion': 'Degree Completion',
    'degree.completedCourses': 'Completed Courses',
    'degree.advancedStanding': 'Advanced Standing',
    'degree.totalEarned': 'Total Earned',
    'degree.remaining': 'Remaining',
    'degree.creditsHeadStart': 'Your {count} AP/IB/transfer credits give you a head start!',
    'degree.milestone25': '1/4 of the way there!',
    'degree.milestone50': 'Halfway done! 🎉',
    'degree.milestone75': 'Almost there! 💪',
    'degree.milestone100': 'Graduation! 🎓',
    'degree.creditsEarned': 'credits earned',
    'degree.creditsRequired': 'credits required',

    // ── GPA & Calculator ──────────────────────────────────
    'gpa.trendTitle': 'Cumulative GPA Trend',
    'gpa.calculatorSubtitle': 'Calculate what you need to achieve your goal',
    'gpa.currentGpa': 'Current GPA',
    'gpa.creditsCompleted': 'Credits Completed',
    'gpa.creditsRemaining': 'Credits Remaining',
    'gpa.targetGpa': 'Target GPA',
    'gpa.requiredGpa': 'Required GPA for Remaining Courses',
    'gpa.equivalentGrade': 'Equivalent to maintaining approximately:',
    'gpa.notAchievable': 'Target Not Achievable',
    'gpa.calculateRequired': 'Calculate Required GPA',
    'gpa.toReach': 'To reach',
    'gpa.withRemaining': 'GPA with',
    'gpa.whatIfScenarios': 'What if scenarios',
    'gpa.scenarioConservative': 'Conservative (B average)',
    'gpa.scenarioStrong': 'Strong (A- average)',
    'gpa.scenarioPerfect': 'Perfect (A average)',
    'gpa.finalGpa': 'Final GPA',
    'gpa.tipsToReach': 'Tips to Reach Your Goal',
    'gpa.calculateAnother': 'Calculate Another Target',
    'gpa.tryDifferent': 'Try Different Target',
    'gpa.impossibleMessage': 'Impossible to achieve. Even with a perfect 4.0 GPA for all remaining courses, your final GPA would only be',
    'gpa.alreadyExceeded': 'You\'ve already exceeded your target! Your current GPA of {current} will reach {target} even if you score 0.0 in remaining courses.',
    'gpa.difficultyEasy': 'Easy',
    'gpa.difficultyModerate': 'Moderate',
    'gpa.difficultyChallenging': 'Challenging',
    'gpa.difficultyDifficult': 'Difficult',
    'gpa.difficultyVeryDifficult': 'Very Difficult',
    'gpa.current': 'Current',
    'gpa.currentGpaLabel': 'Current GPA',
    'gpa.semester': 'semester',
    'gpa.semesters': 'semesters',
    'gpa.semesterShort': 'Sem',
    'gpa.addGradesPrompt': 'Add semester grades to see your GPA trend',
    'gpa.courses': 'courses',

    // ── Mark Complete Modal ───────────────────────────────
    'modal.markComplete': 'Mark Course as Completed',
    'modal.term': 'Term',
    'modal.year': 'Year',
    'modal.grade': 'Grade (optional)',
    'modal.notSpecified': 'Not specified',
    'modal.fall': 'Fall',
    'modal.winter': 'Winter',
    'modal.summer': 'Summer',

    // ── Achievements & Insights ───────────────────────────
    'achievements.title': 'Achievements',
    'insights.title': 'Personalized Insights',
    'insights.subtitle': 'Recommendations based on your profile and activity',
    'insights.completeProfile': 'Complete your profile and interact with the AI advisor to get personalized recommendations!',

    // ── Course Timeline ───────────────────────────────────
    'timeline.noCourses': 'No completed courses yet. Mark courses as taken in the Saved tab!',

    // ── Forum ─────────────────────────────────────────────
    'forum.comingSoon': 'Coming Soon',
    'forum.title': 'McGill Community Forum',
    'forum.launchDate': 'Launching Spring 2026',
    'forum.whatsComingTitle': "What's Coming",
    'forum.sneakPeek': 'Sneak Peek',
    'forum.sneakPeekSubtitle': "Here's what the forum will look like",
    'forum.recentDiscussions': 'Recent Discussions',
    'forum.beAmongFirst': 'Be Among the First',
    'forum.joinWaitlist': 'Join the waitlist to get early access and help shape the community',
    'forum.subtitle': 'Connect with fellow students, share experiences, and get advice from the McGill community',
    'forum.feature1Title': 'Ask Questions',
    'forum.feature1Desc': 'Get help from fellow McGill students on courses, professors, and academics',
    'forum.feature2Title': 'Connect with Classmates',
    'forum.feature2Desc': 'Find study groups, share notes, and collaborate on projects',
    'forum.feature3Title': 'Share Experiences',
    'forum.feature3Desc': 'Review courses, rate professors, and help others make informed decisions',
    'forum.feature4Title': 'Course Planning',
    'forum.feature4Desc': 'Discuss degree requirements, prerequisites, and academic pathways',
    'forum.newPost': '+ New Post',
    'forum.replies': 'replies',
    'forum.likes': 'likes',
    'forum.joinWaitlistBtn': 'Join Waitlist',
    'forum.waitlistPlaceholder': 'Enter your email to join the waitlist',
    'forum.waitlistSuccess': "You're on the list! We'll notify you when the forum launches.",
    'forum.comingSoonLabel': 'Coming Soon',

    // ── Auth / Login ──────────────────────────────────────
    'auth.aiAdvisor': 'AI Academic Advisor',
    'auth.aiRecommendations': 'AI-Powered Recommendations',
    'auth.historicalData': 'Historical Grade Data',
    'auth.coursePlanning': 'Personalized Course Planning',
    'auth.username': 'Username',
    'auth.email': 'Email Address',
    'auth.password': 'Password',

    // ── Errors ────────────────────────────────────────────
    'error.authInitFailed': 'Unable to initialize authentication',
    'error.refreshPage': 'Please refresh the page or check your internet connection.',
    'error.profileSetupIssue': 'Profile Setup Issue',
    'error.profileSetupDesc': 'There was an issue setting up your profile. Please sign out and try again.',
    'error.sessionSetup': 'Setting up your session...',
    'error.loadingProfile': 'Loading your profile...',

    // ── Sign Out Confirmation ─────────────────────────────
    'signOut.confirm': 'Are you sure you want to sign out?',
    'signOut.button': 'Sign Out',

    // ── Degree Planning ───────────────────────────────────
    'dp.generatingRecs': 'Generating personalized recommendations…',
    'dp.retry': 'Retry',
    'dp.loadingRequirements': 'Loading requirements…',
    'dp.requirementsNotLoaded': 'Requirements not loaded yet.',
    'dp.loadRequirements': 'Load Requirements',
    'dp.loading': 'Loading…',
    'dp.notAvailable': "Detailed requirements for {programs} are not yet available. We're working on adding more programs!",
    'dp.browseDegreeReqs': 'You can still browse available programs in the Degree Requirements tab.',
    'dp.notAvailableShort': 'Detailed requirements for {program} are not yet available.',
    'dp.checkDegreeReqs': 'Check the Degree Requirements tab to browse all available programs.',
    'dp.credits': 'credits',
    'dp.electives': '✦ Electives',
    'dp.tabCore': 'Core: {label}',
    'dp.tabConcentration': 'Concentration: {label}',
    'dp.tabScience': 'Science: {label}',
    'dp.tabMinor': 'Minor: {label}',
    'dp.tabMajor': 'Major: {label}',
    'dp.ringCore': 'Core',
    'dp.ringMajor': 'Major',
    'dp.ringMinor': 'Minor',
    'dp.ringConcentration': 'Concentration',
    'dp.foundationWaived': 'Foundation Year Waived',
    'dp.foundationWaivedDesc': 'Your {count} transfer credits exempt you from U0 Foundation requirements',
    'dp.foundationWaivedNote': '(note: 30 cr for full exemption)',
    'dp.myDegree': 'My Degree',
    'dp.myCourses': 'My Degree',
    'dp.degreeRequirements': 'Degree Requirements',
    'dp.studyAbroad': 'Study Abroad',
    'dp.transcript': 'Transcript',
    'dp.syllabuses': 'Syllabi',
    'dp.na': '(N/A)',
    'dp.statusTransfer': 'Transfer',
    'dp.statusDone': 'Done',
    'dp.statusTaking': 'Taking',
    'dp.creditsOf': '{earned} / {total} credits',
    'dp.myProgramRequirements': 'My Program Requirements',
    'dp.welcomeTitle': 'Degree Requirements',
    'dp.welcomeDesc': 'Select a program from the sidebar to see its full requirements, your progress, and recommended courses.',
    'dp.programsAvailable': '{count} programs available',
    'dp.programAvailable': '{count} program available',
    'dp.loadBtn': 'Load Requirements',
    'dp.loadingSpinner': 'Loading requirements…',
    'dp.notFoundTitle': 'Program Not Yet Available',
    'dp.notFoundDesc': "Detailed requirements for this program haven't been added yet. We're working on expanding our coverage!",
    'dp.notFoundHint': 'Try selecting a different program from the sidebar, or check back later.',
    'dp.loadError': 'Could not load program details. Please try again.',

    // ── Academic Brief ────────────────────────────────────
    'brief.title': 'Academic Brief',
    'brief.updated': 'Updated {time}',
    'brief.refresh': 'Refresh cards',
    'brief.all': 'All',
    'brief.saved': 'Saved',
    'brief.history': 'History',
    'brief.preparing': 'Your academic brief is being prepared.',
    'brief.generateNow': 'Generate Now',
    'brief.noHistory': 'No chat history yet. Start a conversation on any card.',
    'brief.noSaved': 'No saved cards yet. Bookmark cards to keep them here.',
    'brief.noCards': 'No {category} cards right now.',
    'brief.placeholder': 'Ask anything about your academics — creates a new chat card',
    'brief.askedByYou': 'Asked by you',
    'brief.savedBadge': 'Saved',
    'brief.pinnedBadge': 'Pinned',
    'brief.deleteCard': 'Delete card',
    'brief.removeBookmark': 'Remove bookmark',
    'brief.bookmark': 'Bookmark',
    'brief.unpin': 'Unpin from sidebar',
    'brief.pin': 'Pin to sidebar',
    'brief.dragReorder': 'Drag to reorder',
    'brief.you': 'You',
    'brief.ai': 'AI',
    'brief.msgs': '{n} msg',
    'brief.msgsPlural': '{n} msgs',
    'brief.errorSend': 'Something went wrong. Please try again.',
    'brief.followUpPlaceholder': 'Ask a follow-up…',
    'brief.catDeadlines': 'Deadlines',
    'brief.catDegree': 'Degree',
    'brief.catCourses': 'Courses',
    'brief.catGrades': 'Grades',
    'brief.catPlanning': 'Planning',
    'brief.catOpportunities': 'Opportunities',
    'brief.catOther': 'Other',
    'brief.timeJustNow': 'just now',
    'brief.time1Min': '1 min ago',
    'brief.timeMins': '{n} mins ago',
    'brief.timeHours': '{n}h ago',
  },

  fr: {
    // ── Sidebar Nav ───────────────────────────────────────
    'nav.chat': 'Chat IA',
    'nav.courses': 'Cours',
    'nav.saved': 'Sauvegardés',
    'nav.calendar': 'Calendrier',
    'nav.forum': 'Forum',
    'nav.profile': 'Profil',
    'nav.degreePlanning': 'Planification académique',

    // ── Sidebar Footer / Popup ────────────────────────────
    'sidebar.settings': 'Paramètres',
    'sidebar.changeLanguage': 'Changer la langue',
    'sidebar.colorTheme': 'Thème de couleur',
    'sidebar.logOut': 'Déconnexion',
    'sidebar.signOut': 'Déconnexion',

    // ── Settings Section Titles ───────────────────────────
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience McGill Advisor',
    'settings.appearance': 'Apparence',
    'settings.notifications': 'Notifications',
    'settings.privacyData': 'Confidentialité et données',
    'settings.preferences': 'Préférences',

    // ── Settings Labels ───────────────────────────────────
    'settings.theme': 'Thème',
    'settings.themeDescription': 'Choisissez votre palette de couleurs préférée',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.auto': 'Auto',
    'settings.emailNotifications': 'Notifications par courriel',
    'settings.emailNotificationsDesc': 'Recevoir des mises à jour par courriel',
    'settings.deadlineReminders': 'Rappels d\'échéance',
    'settings.deadlineRemindersDesc': 'Être notifié des échéances à venir',
    'settings.calendarNotifications': 'Paramètres de notifications du calendrier',
    'settings.notifMethod': 'Méthode de notification par défaut',
    'settings.notifMethodDesc': 'Comment vous souhaitez être rappelé par défaut',
    'settings.notifEmail': 'Courriel',
    'settings.notifSMS': 'Texto (SMS)',
    'settings.notifBoth': 'Les deux',
    'settings.notifNone': 'Aucune',
    'settings.notifEmailAddr': 'Courriel de notification',
    'settings.notifEmailAddrDesc': 'Adresse courriel pour les rappels du calendrier',
    'settings.notifPhone': 'Numéro de téléphone',
    'settings.notifPhoneDesc': 'Numéro pour les rappels par SMS',
    'settings.notifTiming': 'Délai de rappel par défaut',
    'settings.notifTimingDesc': 'Quand envoyer les rappels par défaut',
    'settings.notifSameDay': 'Même jour',
    'settings.notifOneDay': '1 jour avant',
    'settings.notifOneWeek': '1 semaine avant',
    'settings.notifEventTypes': 'Me notifier pour',
    'settings.notifEventTypesDesc': "Types d'événements pour lesquels recevoir des rappels",
    'settings.notifSave': 'Sauvegarder les préférences',
    'settings.notifSaved': 'Sauvegardé!',
    'settings.courseUpdates': 'Mises à jour des cours',
    'settings.courseUpdatesDesc': 'Notifications sur les changements de cours',
    'settings.profileVisibility': 'Visibilité du profil',
    'settings.profileVisibilityDesc': 'Qui peut voir votre profil',
    'settings.private': 'Privé',
    'settings.friendsOnly': 'Amis seulement',
    'settings.public': 'Public',
    'settings.shareProgress': 'Partager le progrès académique',
    'settings.shareProgressDesc': 'Permettre aux autres de voir votre progrès',
    'settings.language': 'Langue',
    'settings.languageDesc': 'Langue de l\'interface',
    'settings.timezone': 'Fuseau horaire',
    'settings.timezoneDesc': 'Votre fuseau horaire local',

    // ── Danger zone ─────────────────────────────────────
    'settings.dangerZone': 'Zone de danger',
    'settings.deleteAccount': 'Supprimer le compte',
    'settings.deleteAccountDesc': 'Supprimez définitivement votre compte et toutes les données associées. Cette action est irréversible.',
    'settings.deleteAccountBtn': 'Supprimer le compte',
    'settings.deleteConfirmTitle': 'Supprimer votre compte ?',
    'settings.deleteConfirmText': 'Cela supprimera définitivement votre compte, tous vos cours, notes, événements de calendrier et préférences. Cette action est irréversible.',
    'settings.deleteConfirmPrompt': 'Tapez SUPPRIMER pour confirmer :',
    'settings.deleteConfirmPlaceholder': 'Tapez SUPPRIMER',
    'settings.deleteConfirmBtn': 'Supprimer définitivement',
    'settings.deleteDeleting': 'Suppression…',
    'settings.deleteError': 'Échec de la suppression. Veuillez réessayer.',
    'settings.exportData': 'Exporter les données',
    'settings.exportYourData': 'Exporter vos données',
    'settings.exportDataDesc': 'Télécharger toutes vos données en JSON',
    'settings.exportModalText': 'Cela téléchargera toutes vos données de profil, cours et paramètres sous forme de fichier JSON. Vous pouvez l\'utiliser pour la sauvegarde ou le transfert de données.',
    'settings.downloadJson': 'Télécharger JSON',
    'settings.dataExported': 'Données exportées avec succès !',

    // ── Profile Labels ────────────────────────────────────
    'profile.personalInfo': 'Informations personnelles',
    'profile.manageDetails': 'Gérer les détails de votre profil',
    'profile.username': 'Nom d\'utilisateur',
    'profile.email': 'Adresse courriel',
    'profile.faculty': 'Faculté',
    'profile.major': 'Majeure principale',
    'profile.additionalMajors': 'Majeures supplémentaires',
    'profile.minor': 'Mineure',
    'profile.primaryMinor': 'Mineure principale',
    'profile.additionalMinors': 'Mineures supplémentaires',
    'profile.concentration': 'Concentration',
    'profile.year': 'Année académique',
    'profile.gpa': 'MPC',
    'profile.currentGpa': 'MPC actuelle',
    'profile.editProfile': 'Modifier le profil',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.changePhoto': 'Changer la photo',
    'profile.notSpecified': 'Non spécifié',
    'profile.notSet': 'Non défini',
    'profile.completeness': 'Complétude du profil',
    'profile.academicInfo': 'Informations académiques',
    'profile.contactInfo': 'Coordonnées',
    'profile.additionalInfo': 'Informations supplémentaires',
    'profile.academicInterests': 'Intérêts académiques',
    'profile.noInterests': 'Aucun intérêt ajouté. Ajoutez vos intérêts académiques pour obtenir des recommandations personnalisées !',

    // ── Profile Tab Sections ──────────────────────────────
    'profile.academicPerformance': 'Performance académique',
    'profile.gpaTip': 'Gardez votre MPC à jour pour de meilleures recommandations de cours',
    'profile.degreeProgress': 'Progrès du diplôme',
    'profile.interestsPreferences': 'Intérêts et préférences',
    'profile.achievements': 'Réalisations',
    'profile.personalizedInsights': 'Recommandations personnalisées',
    'profile.insightsSubtitle': 'Recommandations basées sur votre profil et votre activité',
    'profile.insightsEmpty': 'Complétez votre profil et interagissez avec le conseiller IA pour obtenir des recommandations personnalisées !',
    'profile.signOutTitle': 'Déconnexion',
    'profile.signOutDescription': 'Se déconnecter de votre compte McGill AI Advisor',
    'profile.mcgillStudent': 'Étudiant McGill',
    'profile.yearNotSet': 'Année non définie',
    'profile.yearLabel': 'Année {year}',

    // ── Profile Form ──────────────────────────────────────
    'profileForm.basicInfo': 'Informations de base',
    'profileForm.enterUsername': 'Entrer le nom d\'utilisateur',
    'profileForm.optional': 'Facultatif',
    'profileForm.displayName': 'Votre nom d\'affichage',
    'profileForm.academicInfo': 'Informations académiques',
    'profileForm.academicInfoDesc': 'Votre faculté, programme et année d\'études',
    'profileForm.selectFaculty': 'Sélectionnez votre faculté',
    'profileForm.selectYear': 'Sélectionnez l\'année',
    'profileForm.selectMajor': 'Sélectionnez votre majeure',
    'profileForm.selectMinor': 'Sélectionnez une mineure (facultatif)',
    'profileForm.performanceInterests': 'Performance et intérêts',
    'profileForm.performanceInterestsDesc': 'Aidez-nous à personnaliser votre expérience',
    'profileForm.gpaScale': 'Échelle de 0.0 - 4.0',
    'profileForm.separateCommas': 'Séparer par des virgules',
    'profileForm.advancedStanding': 'Équivalences',
    'profileForm.advancedStandingDesc': 'Crédits AP, IB ou de transfert',
    'profileForm.courseCode': 'Code du cours',
    'profileForm.credits': 'Crédits',
    'profileForm.addCourse': 'Ajouter un cours',
    'profileForm.removeCourse': 'Retirer',
    'profileForm.forDoubleMajors': 'Pour les concentrations doubles/conjointes',
    'profileForm.multipleMinors': 'Si vous avez plusieurs mineurs',
    'profileForm.verified': 'Vérifié',
    'profileForm.completeBetterRecs': 'Complétez votre profil pour obtenir de meilleures recommandations',
    'profileForm.noInterestsAdded': 'Aucun intérêt ajouté',

    // ── Common ────────────────────────────────────────────
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.saveChanges': 'Sauvegarder les modifications',
    'common.delete': 'Supprimer',
    'common.confirm': 'Confirmer',
    'common.areYouSure': 'Êtes-vous sûr ?',
    'common.cancel': 'Annuler',
    'common.calculator': 'Calculateur',
    'common.english': 'English',
    'common.french': 'Français',
    'common.user': 'Utilisateur',
    'common.na': 'N/D',
    'common.reloadPage': 'Recharger la page',

    // ── Chat ──────────────────────────────────────────────
    'chat.placeholder': 'Posez-moi n\'importe quelle question sur les cours, la planification ou les études à McGill...',
    'chat.send': 'Envoyer',
    'chat.sending': 'Envoi...',
    'chat.newChat': 'Nouveau chat',
    'chat.chatSession': 'Session de chat',
    'chat.chatHistory': 'Historique des chats',
    'chat.noPreviousChats': 'Aucun chat précédent',
    'chat.loadingHistory': 'Chargement de l\'historique...',
    'chat.failedToSend': 'Échec de l\'envoi du message. Veuillez réessayer.',
    'chat.failedToLoad': 'Échec du chargement de l\'historique',
    'chat.dropFiles': 'Déposez les fichiers ici pour les joindre',
    'chat.dropFilesSubtext': 'PDF, Images, Fichiers texte (max 32 Mo)',
    'chat.welcomeMessage': 'Bonjour ! Je suis votre conseiller académique IA de McGill. Comment puis-je vous aider à planifier vos cours aujourd\'hui ?',
    'chat.errorSending': 'Échec de l\'envoi du message. Veuillez réessayer.',
    'chat.historyTitle': 'Historique des chats',
    'chat.showHistory': 'Afficher l\'historique des chats',
    'chat.closeHistory': 'Fermer l\'historique',

    // ── Badges ────────────────────────────────────────────
    'badges.unlocked': '{count} de {total} débloqués',
    'badges.gettingStarted': 'Premiers pas',
    'badges.gettingStartedDesc': 'Configurer votre profil',
    'badges.courseExplorer': 'Explorateur de cours',
    'badges.courseExplorerDesc': '10+ cours sauvegardés',
    'badges.chatMaster': 'Maître du chat',
    'badges.chatMasterDesc': '50+ conversations IA',
    'badges.wellRounded': 'Bien équilibré',
    'badges.wellRoundedDesc': 'Cours dans 5+ départements',
    'badges.deansList': 'Liste du doyen',
    'badges.deansListDesc': 'MPC supérieure à 3.7',
    'badges.earlyBird': 'Lève-tôt',
    'badges.earlyBirdDesc': 'Planifier le prochain trimestre tôt',
    'badges.mcgillVeteran': 'Vétéran de McGill',
    'badges.mcgillVeteranDesc': 'Compléter 60+ crédits',
    'badges.scholar': 'Érudit',
    'badges.scholarDesc': 'Compléter 90+ crédits',
    'badges.almostThere': 'Presque là !',
    'badges.almostThereDesc': 'Compléter 100+ crédits',

    // ── Insights ──────────────────────────────────────────
    'insights.basedOnInterests': 'Selon vos intérêts',
    'insights.exploreCourses': 'Explorer les cours en {interests}',
    'insights.peersAlsoTook': 'Les étudiants de votre majeure ont aussi pris',
    'insights.frequentlyAsk': 'Vous demandez fréquemment à propos de',
    'insights.outstandingPerformance': 'Performance exceptionnelle',
    'insights.honoursProgramsQualify': 'Votre MPC vous qualifie pour les programmes d\'honneur et opportunités compétitives',
    'insights.almostThere': 'Presque là !',
    'insights.creditsUntilGrad': 'Seulement {count} crédits jusqu\'à la graduation',

    // ── Courses ───────────────────────────────────────────
    'courses.searchPlaceholder': 'Rechercher des cours (ex. COMP202, Introduction à la programmation)...',
    'courses.searching': 'Recherche...',
    'courses.filters': 'Filtres',
    'courses.sortBy': 'Trier par :',
    'courses.relevance': 'Pertinence',
    'courses.addToSaved': 'Ajouter aux favoris',
    'courses.removeFromSaved': 'Retirer des favoris',
    'courses.markCompleted': 'Marquer comme complété',
    'courses.markNotCompleted': 'Marquer comme non complété',
    'courses.courseDetails': 'Détails du cours',
    'courses.prerequisites': 'Prérequis',
    'courses.credits': 'Crédits',
    'courses.sections': 'Sections',
    'courses.instructor': 'Professeur',
    'courses.rating': 'Évaluation',
    'courses.difficulty': 'Difficulté',
    'courses.reviews': 'Avis',
    'courses.wouldRetake': 'Reprendrait',
    'courses.loadingDetails': 'Chargement des détails du cours...',
    'courses.noResults': 'Aucun cours trouvé correspondant à votre recherche.',
    'courses.failedSearch': 'Échec de la recherche de cours. Veuillez réessayer.',
    'courses.failedDetails': 'Échec du chargement des détails du cours.',
    'courses.explorerTitle': 'Explorateur de cours avec évaluations des professeurs',
    'courses.explorerDesc': 'Recherchez parmi les cours de McGill avec des données historiques de notes et des évaluations RateMyProfessor en direct.',
    'courses.failedUpdate': 'Échec de la mise à jour des favoris',
    'courses.failedCompleted': 'Échec de la mise à jour des cours complétés',
    'courses.failedMarkCompleted': 'Échec du marquage du cours comme complété',
    'courses.foundResults': '{count} cours trouvé',
    'courses.foundResultsPlural': '{count} cours trouvés',
    'courses.sectionsAvailable': '{count} section disponible',
    'courses.sectionsAvailablePlural': '{count} sections disponibles',
    'courses.newSearch': 'Nouvelle recherche',
    'courses.backToResults': 'Retour aux résultats',
    'courses.average': 'Moyenne',
    'courses.professorRating': 'Évaluation du professeur',
    'courses.search': 'Rechercher',
    'courses.sortRatingHigh': '⭐ Évaluation (haute à basse)',
    'courses.sortRatingLow': '⭐ Évaluation (basse à haute)',
    'courses.sortNameAZ': '📚 Nom du cours (A-Z)',
    'courses.sortNameZA': '📚 Nom du cours (Z-A)',
    'courses.sortInstructorAZ': '👤 Professeur (A-Z)',
    'courses.sortInstructorZA': '👤 Professeur (Z-A)',
    'courses.vsbLabel': 'Constructeur d\'horaire visuel',
    'courses.vsbDesc': 'Planifiez votre horaire sur le constructeur officiel de McGill',

    // ── Study Abroad ───────────────────────────────────────
    'sa.title': 'Études à l\'étranger et stages sur le terrain',
    'sa.subtitle': 'Échanges, semestres sur le terrain, stages et études à l\'extérieur — les crédits comptent pour votre diplôme McGill.',
    'sa.browse': 'Explorer',
    'sa.saved': 'Sauvegardés',
    'sa.statPartners': 'universités partenaires',
    'sa.statCountries': 'pays',
    'sa.statTypes': 'types de programmes',
    'sa.searchPlaceholder': 'Rechercher des programmes, destinations…',
    'sa.programs': '{count} programmes',
    'sa.program': '{count} programme',
    'sa.matchingFilters': ' correspondant aux filtres',
    'sa.clearFilters': 'Effacer les filtres',
    'sa.noMatch': 'Aucun programme ne correspond à vos filtres.',
    'sa.noSaved': 'Aucun programme sauvegardé.',
    'sa.noSavedSub': 'Explorez les programmes et cliquez sur le signet pour les sauvegarder.',
    'sa.footerText': 'Vous cherchez quelque chose qui n\'est pas listé ici ?',
    'sa.footerLink': 'Visiter McGill à l\'étranger',
    'sa.eligibility': 'Admissibilité',
    'sa.deadlines': 'Dates limites',
    'sa.saveBookmark': 'Sauvegarder',
    'sa.removeBookmark': 'Retirer le signet',
    'sa.typeAll': 'Tous',
    'sa.typeExchange': 'Échange',
    'sa.typeField': 'Études sur le terrain',
    'sa.typeCourses': 'Cours à l\'étranger',
    'sa.typeInternship': 'Stage / Co-op',
    'sa.typeIut': 'TIU / Études ailleurs',
    'sa.regionAll': 'Toutes les régions',
    'sa.regionEurope': 'Europe',
    'sa.regionAmericas': 'Amériques',
    'sa.regionAsia': 'Asie-Pacifique',
    'sa.regionAfrica': 'Afrique et Moyen-Orient',
    'sa.regionCanada': 'Canada',
    'sa.badgeExchange': 'Échange',
    'sa.badgeField': 'Terrain',
    'sa.badgeCourses': 'Cours à l\'étranger',
    'sa.badgeInternship': 'Stage',
    'sa.badgeIut': 'TIU / Ailleurs',

    // ── Feedback ───────────────────────────────────────────
    'fb.button': 'Commentaires',
    'fb.title': 'Envoyer des commentaires',
    'fb.modePrompt': 'Que souhaitez-vous nous dire ?',
    'fb.modeGeneral': 'Commentaire général',
    'fb.modeGeneralSub': 'Rapports de bogues, suggestions, autre chose',
    'fb.modeMissing': 'Cours manquant',
    'fb.modeMissingSub': 'Vous ne trouvez pas un cours ?',
    'fb.generalDesc': 'Dites-nous ce qui fonctionne, ce qui est cassé, ou ce que vous aimeriez voir.',
    'fb.generalPlaceholder': 'Vos commentaires...',
    'fb.missingDesc': 'Dites-nous quel cours vous n\'avez pas trouvé et nous travaillerons à l\'ajouter.',
    'fb.missingPlaceholder': 'Code de cours, p. ex. POLS 340',
    'fb.missingExtra': 'Contexte supplémentaire ? (facultatif)',
    'fb.back': '← Retour',
    'fb.send': 'Envoyer',
    'fb.sending': 'Envoi…',
    'fb.submit': 'Soumettre',
    'fb.success': 'Merci ! Nous avons reçu vos commentaires.',
    'fb.duplicate': 'Il semble que vous ayez déjà soumis ceci récemment.',
    'fb.close': 'Fermer',

    // ── Clubs ──────────────────────────────────────────────
    'clubs.title': 'Clubs étudiants',
    'clubs.subtitle': 'Découvrez, rejoignez et synchronisez les clubs McGill à votre calendrier',
    'clubs.submitBtn': 'Soumettre un club',
    'clubs.tabExplore': 'Explorer',
    'clubs.tabMine': 'Mes clubs',
    'clubs.searchPlaceholder': 'Rechercher des clubs par nom, mot-clé ou catégorie…',
    'clubs.sortDefault': 'Ordre par défaut',
    'clubs.sortMembers': 'Plus de membres',
    'clubs.sortName': 'Nom A→Z',
    'clubs.filterAll': 'Tous',
    'clubs.loading': 'Chargement des clubs…',
    'clubs.loadingMine': 'Chargement de vos clubs…',
    'clubs.noResults': 'Aucun club trouvé',
    'clubs.noResultsHint': 'Essayez d\'autres mots-clés ou',
    'clubs.noResultsSubmit': 'soumettez un nouveau club',
    'clubs.results': '{count} clubs',
    'clubs.result': '{count} club',
    'clubs.inCategory': ' dans',
    'clubs.matching': ' correspondant à',
    'clubs.showingFirst': ' — affichage des {count} premiers',
    'clubs.loadMore': 'Charger plus de clubs',
    'clubs.loadingMore': 'Chargement…',
    'clubs.noJoined': 'Aucun club rejoint',
    'clubs.noJoinedHint': "Trouvez quelque chose qui vous passionne dans l'onglet Explorer.",
    'clubs.browseBtn': 'Explorer les clubs',
    'clubs.joinedToast': '{name} rejoint !',
    'clubs.back': 'Retour',
    'clubs.leaveClub': 'Quitter le club',
    'clubs.joinClub': 'Rejoindre le club',
    'clubs.members': 'Membres',
    'clubs.meets': 'Réunions',
    'clubs.location': 'Lieu',
    'clubs.about': 'À propos',
    'clubs.calendarSync': 'Synchronisation calendrier',
    'clubs.calSyncDesc': 'Synchronisez les réunions de ce club avec votre onglet Calendrier.',
    'clubs.synced': 'Synchronisé',
    'clubs.notSynced': 'Non synchronisé',
    'clubs.linksContact': 'Liens et contact',
    'clubs.visitWebsite': 'Visiter le site',
    'clubs.joinedBadge': 'Rejoint',
    'clubs.calOn': 'Calendrier actif',
    'clubs.calOff': 'Calendrier inactif',
    'clubs.leave': 'Quitter',
    'clubs.joinedBtn': 'Rejoint !',
    'clubs.joinBtn': 'Rejoindre',
    'clubs.syncBtn': 'Synchroniser',
    'clubs.submitModalTitle': 'Soumettre un club',
    'clubs.submitModalSub': 'Aidez à faire grandir le répertoire des clubs McGill',
    'clubs.submitSuccess': 'Soumis !',
    'clubs.submitSuccessDesc': 'Votre club a été mis en file d\'attente pour révision et sera ajouté bientôt.',
    'clubs.done': 'Terminé',
    'clubs.fieldName': 'Nom du club',
    'clubs.fieldNamePlaceholder': 'ex. Club d\'échecs McGill',
    'clubs.fieldCategory': 'Catégorie',
    'clubs.fieldCategoryDefault': 'Sélectionner…',
    'clubs.fieldLocation': 'Lieu',
    'clubs.fieldLocationPlaceholder': 'ex. Burnside 105',
    'clubs.fieldDesc': 'Description',
    'clubs.fieldDescPlaceholder': 'Que fait ce club ?',
    'clubs.fieldSchedule': 'Horaire des réunions',
    'clubs.fieldSchedulePlaceholder': 'Mardis 17h–19h',
    'clubs.fieldEmail': 'Courriel de contact',
    'clubs.fieldUrl': 'URL du site web',
    'clubs.cancel': 'Annuler',
    'clubs.submitting': 'Envoi…',
    'clubs.submitClub': 'Soumettre le club',
    'clubs.required': 'Requis',
    'clubs.catAcademic': 'Académique',
    'clubs.catEngineering': 'Génie et technologie',
    'clubs.catProfessional': 'Professionnel',
    'clubs.catDebate': 'Débat et politique',
    'clubs.catAthletics': 'Sport et loisirs',
    'clubs.catArts': 'Arts et culture',
    'clubs.catEnvironment': 'Environnement',
    'clubs.catHealth': 'Santé et bien-être',
    'clubs.catCommunity': 'Service communautaire',
    'clubs.catInternational': 'International',
    'clubs.catScience': 'Science',
    'clubs.catSocial': 'Social',
    'clubs.catSpiritual': 'Spirituel et religieux',

    // ── Auth / Login ────────────────────────────────────────
    'auth.brandHeadline': 'Votre conseiller académique IA.',
    'auth.brandSub': 'Planification de cours personnalisée, données historiques de notes et orientation intelligente — tout en un seul endroit.',
    'auth.feature1': 'Recommandations de cours propulsées par l\'IA',
    'auth.feature2': 'Données de notes historiques pour plus de 10 000 sections',
    'auth.feature3': 'Planification de diplôme adaptée à votre programme et vos objectifs',
    'auth.feature4': 'Soutien académique 24/7 par clavardage',
    'auth.tabSignIn': 'Connexion',
    'auth.tabCreate': 'Créer un compte',
    'auth.titleForgot': 'Réinitialiser le mot de passe',
    'auth.titleLogin': 'Bon retour',
    'auth.titleSignup': 'Commencer',
    'auth.subForgot': 'Nous enverrons un lien de réinitialisation à votre courriel.',
    'auth.subLogin': 'Connectez-vous pour continuer votre parcours académique.',
    'auth.subSignup': 'Créez votre compte Symbolos gratuit.',
    'auth.labelUsername': "Nom d'utilisateur",
    'auth.labelEmail': 'Adresse courriel',
    'auth.labelPassword': 'Mot de passe',
    'auth.forgotLink': 'Mot de passe oublié ?',
    'auth.showPassword': 'Afficher le mot de passe',
    'auth.hidePassword': 'Masquer le mot de passe',
    'auth.passwordHint': 'Au moins 8 caractères avec majuscules, minuscules et chiffres',
    'auth.strengthWeak': 'Faible',
    'auth.strengthFair': 'Passable',
    'auth.strengthGood': 'Bien',
    'auth.strengthStrong': 'Fort',
    'auth.btnForgot': 'Envoyer le lien',
    'auth.btnLogin': 'Se connecter',
    'auth.btnSignup': 'Créer un compte',
    'auth.loadingForgot': 'Envoi…',
    'auth.loadingLogin': 'Connexion…',
    'auth.loadingSignup': 'Création du compte…',
    'auth.backToLogin': '← Retour à la connexion',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.signUpLink': "S'inscrire",
    'auth.signInLink': 'Se connecter',
    'auth.resetSent': 'Si un compte existe avec ce courriel, un lien de réinitialisation a été envoyé.',
    'auth.accountCreated': 'Compte créé ! Redirection…',
    'auth.genericError': 'Une erreur est survenue. Veuillez réessayer.',
    'auth.langToggle': 'English',

    // ── Onboarding / ProfileSetup ───────────────────────
    'ps.txTitle': 'Importer votre relevé de notes',
    'ps.txSubtitle': 'Nous allons automatiquement récupérer vos cours, notes, GPA et informations de programme.',
    'ps.stepTranscript': 'Relevé de notes',
    'ps.stepSyllabi': 'Plans de cours',
    'ps.dropTranscript': 'Déposez votre relevé de notes non officiel ici',
    'ps.dropBrowse': 'ou cliquez pour parcourir · PDF seulement · max 10 Mo',
    'ps.importTranscript': 'Importer le relevé',
    'ps.skipForNow': 'Passer pour l\'instant',
    'ps.hintTranscript': 'Vous pouvez aussi le faire plus tard depuis l\'onglet <strong>Profil</strong> — trouvez <strong>Importer le relevé</strong> dans la carte Progression.',
    'ps.txUploading': 'Importation du relevé…',
    'ps.txUploadingSub': 'Claude lit vos cours, notes et informations de programme.',
    'ps.txDone': 'Relevé importé !',
    'ps.txDoneSub': 'Votre historique académique est prêt. Ensuite, téléversez vos plans de cours.',
    'ps.txCompletedLabel': 'cours complétés',
    'ps.txCurrentLabel': 'cours actuels',
    'ps.txProfileUpdated': 'profil mis à jour',
    'ps.continueSyllabi': 'Continuer vers les plans de cours',
    'ps.txError': 'Échec de l\'importation',
    'ps.tryAgain': 'Réessayer',
    'ps.skipSyllabi': 'Passer aux plans de cours',
    'ps.txPdfOnly': 'Veuillez téléverser un fichier PDF.',
    'ps.txTooLarge': 'Le fichier doit être inférieur à 10 Mo.',
    'ps.sylTitle': 'Téléverser vos plans de cours',
    'ps.sylSubtitle': 'Nous allons extraire les horaires, examens et infos professeur — et remplir votre calendrier automatiquement.',
    'ps.sylInfo1': 'Horaires de cours et salles ajoutés à votre calendrier',
    'ps.sylInfo2': 'Professeur, heures de bureau et coordonnées',
    'ps.sylInfo3': 'Examens et échéances de travaux avec rappels',
    'ps.dropSyllabi': 'Déposez les PDFs de plans de cours ici',
    'ps.dropSyllabiSub': 'Tous à la fois · PDF seulement · max 15 Mo chacun',
    'ps.addMore': 'Ajouter',
    'ps.importSyllabi': 'Importer les plans',
    'ps.importSyllabusCount': 'Importer {count} plan de cours',
    'ps.importSyllabiCount': 'Importer {count} plans de cours',
    'ps.sylUploading': 'Traitement de vos plans de cours…',
    'ps.sylUploadingSub': 'Claude lit les horaires, examens et infos professeur de {count} fichier.',
    'ps.sylUploadingSubPlural': 'Claude lit les horaires, examens et infos professeur de {count} fichiers.',
    'ps.sylDone': 'Plans de cours importés !',
    'ps.sylDoneSub': 'Votre calendrier et vos profils de cours ont été mis à jour.',
    'ps.sylEventsLabel': 'événements de calendrier ajoutés',
    'ps.sylCoursesLabel': '{count} cours enrichi',
    'ps.sylCoursesLabelPlural': '{count} cours enrichis',
    'ps.toDashboard': 'Aller au tableau de bord',
    'ps.hintSyllabi': 'Vous pouvez téléverser des plans de cours à tout moment depuis l\'onglet <strong>Calendrier</strong> ou <strong>Profil</strong>.',
    'ps.sylError': 'Échec de l\'importation',
    'ps.skipDashboard': 'Passer au tableau de bord',
    'ps.loading': 'Chargement…',
    'ps.sylPdfOnly': 'Veuillez téléverser uniquement des fichiers PDF (max 15 Mo chacun).',

    // ── Calendar ──────────────────────────────────────────
    'calendar.today': 'Aujourd\'hui',
    'calendar.month': 'Mois',
    'calendar.week': 'Semaine',
    'calendar.day': 'Jour',
    'calendar.addEvent': 'Ajouter un événement',
    'calendar.announcements': 'Annonces',
    'calendar.exportBtn': 'Exporter',
    'calendar.exportICS': 'Télécharger le fichier .ics',
    'calendar.exportGoogleHelp': 'Importer dans Google Agenda',
    'calendar.addToGoogle': 'Ajouter à Google Agenda',
    'calendar.academicDates': 'Académique McGill',
    'calendar.unionEvents': 'Union étudiante',
    'calendar.clubEvents': 'Événement de club',
    'calendar.personalEvents': 'Personnel',
    'calendar.remindersSet': 'Rappels programmés!',
    'calendar.noUpcoming': 'Aucun événement à venir.',
    'calendar.subtitle': 'Dates académiques, événements et rappels',
    'calendar.calendarView': 'Calendrier',
    'calendar.addEventBtn': 'Ajouter',
    'calendar.prevMonth': 'Mois précédent',
    'calendar.nextMonth': 'Mois suivant',
    'calendar.todayBtn': "Aujourd\'hui",
    'calendar.eventTitle': "Titre de l'événement",
    'calendar.eventTitlePlaceholder': "ex. Groupe d'étude, Réunion de club",
    'calendar.date': 'Date',
    'calendar.time': 'Heure (optionnel)',
    'calendar.eventType': "Type d'événement",
    'calendar.groupCategory': "Groupe / Catégorie (optionnel)",
    'calendar.groupPlaceholder': "ex. Club de maths, AÉUM",
    'calendar.description': 'Description (optionnel)',
    'calendar.descPlaceholder': "Ajoutez des détails sur cet événement…",
    'calendar.reminders': 'Rappels',
    'calendar.notifyVia': 'Me notifier par',
    'calendar.email': 'Courriel',
    'calendar.sendingTo': 'Envoi à',
    'calendar.sms': 'Texto (SMS)',
    'calendar.emailAddress': 'Adresse courriel',
    'calendar.phoneNumber': 'Numéro de téléphone',
    'calendar.whenToRemind': 'Quand me rappeler',
    'calendar.remind7Days': '7 jours avant',
    'calendar.remind1Day': '1 jour avant',
    'calendar.addEventTitle': 'Ajouter un événement',
    'calendar.editEventTitle': "Modifier l'événement",
    'calendar.saveChanges': 'Sauvegarder',
    'calendar.cancel': 'Annuler',
    'calendar.delete': 'Supprimer',
    'calendar.editEvent': 'Modifier',
    'calendar.reminderSet': 'Rappel courriel configuré (7 jours et 1 jour avant)',
    'calendar.daysAgo': 'j passés',
    'calendar.today2': "Aujourd'hui!",
    'calendar.inDays': 'dans',
    'calendar.inDaysSuffix': 'j',
    'calendar.upcomingIn7': 'dans les 7 prochains jours',
    'calendar.event': 'événement',
    'calendar.events': 'événements',
    'calendar.tomorrow': 'Demain',
    'calendar.inXDays': 'Dans {n} jours',
    'calendar.mcgillOfficial': 'McGill officiel',
    'cal.moreDots': 'de plus',

    // ── Calendar static event titles (FR) ─────────────────
    'cal.fallBegins': 'Début du semestre d\'automne',
    'cal.fallMidterms': 'Période des examens de mi-session (automne)',
    'cal.winterMidterms': 'Période des examens de mi-session (hiver)',
    'cal.cancelRegistration': 'Date limite pour annuler l\'inscription',
    'cal.withdrawalRefund': 'Date limite de retrait avec remboursement',
    'cal.easterMonday': 'Lundi de Pâques (pas de cours)',
    'cal.makeupDay': 'Journée de récupération (horaire vendredi)',
    'cal.studyDay': 'Journée d\'étude (pas de cours)',
    'cal.addDropFall': 'Date limite d\'ajout/abandon (automne)',
    'cal.thanksgiving': 'Action de grâce (pas de cours)',
    'cal.fallReadingWeek': 'Semaine de lecture d\'automne',
    'cal.withdrawalFall': 'Date limite de retrait (automne)',
    'cal.lastDayFall': 'Dernier jour de cours d\'automne',
    'cal.fallExamsBegin': 'Début de la période d\'examens d\'automne',
    'cal.fallExamsEnd': 'Fin de la période d\'examens d\'automne',
    'cal.winterBegins': 'Début du semestre d\'hiver',
    'cal.addDropWinter': 'Date limite d\'ajout/abandon (hiver)',
    'cal.winterReadingWeek': 'Semaine de lecture d\'hiver',
    'cal.withdrawalWinter': 'Date limite de retrait (hiver)',
    'cal.goodFriday': 'Vendredi saint (pas de cours)',
    'cal.lastDayWinter': 'Dernier jour de cours d\'hiver',
    'cal.winterExamsBegin': 'Début de la période d\'examens d\'hiver',
    'cal.winterExamsEnd': 'Fin de la période d\'examens d\'hiver',
    'cal.registration': 'Ouverture des inscriptions aux cours',
    'cal.convocation': 'Collation des grades (printemps)',
    'cal.ssmuGA': 'Assemblée générale de l\'AÉUM',
    'cal.froshWeek': 'Lancement de la semaine d\'initiation',
    'cal.hackathon': 'Hackathon McGill 2025',
    'cal.careerFair': 'Foire des carrières en génie',
    'cal.symposium': 'Symposium arts et sciences',
    'cal.foodFestival': 'Festival gastronomique international',
    'cal.studyBreak': 'Pause sociale avant les examens finaux',
    'cal.catSSMU': 'AÉUM',
    'cal.catCSClub': 'Club informatique',
    'cal.catEUS': 'AEG',
    'cal.catArts': 'Conseil des arts',
    'cal.descSSMUGA': 'Assemblée générale d\'hiver — tous les étudiants sont les bienvenus.',
    'cal.descFrosh': 'Cérémonie d\'ouverture de la semaine d\'initiation 2025.',
    'cal.descHack': 'Hackathon de 24 heures ouvert à toutes les facultés.',
    'cal.descCareer': 'Foire annuelle de l\'Association des étudiants en génie.',
    'cal.descSymp': 'Présentations de recherche étudiante.',
    'cal.descFood': 'Célébrez les cultures du monde sur le campus.',
    'cal.descStudyBreak': 'Collations gratuites et détente avant les examens finaux.',

    // ── Saved Courses ─────────────────────────────────────
    'saved.savedCourses': 'Cours sauvegardés',
    'saved.completed': 'Complétés',
    'saved.noSavedCourses': 'Aucun cours sauvegardé',
    'saved.noSavedCoursesDesc': 'Sauvegardez des cours depuis l\'explorateur pour les voir ici',
    'saved.noCompletedCourses': 'Aucun cours complété',
    'saved.noCompletedCoursesDesc': 'Marquez des cours comme complétés pour suivre votre progrès',

    // ── Degree Progress ───────────────────────────────────
    'degree.completion': 'Avancement du diplôme',
    'degree.completedCourses': 'Cours complétés',
    'degree.advancedStanding': 'Équivalences',
    'degree.totalEarned': 'Total obtenu',
    'degree.remaining': 'Restant',
    'degree.creditsHeadStart': 'Vos {count} crédits AP/IB/transfert vous donnent une longueur d\'avance !',
    'degree.milestone25': 'Un quart du chemin !',
    'degree.milestone50': 'À mi-chemin ! 🎉',
    'degree.milestone75': 'Presque là ! 💪',
    'degree.milestone100': 'Graduation ! 🎓',
    'degree.creditsEarned': 'crédits obtenus',
    'degree.creditsRequired': 'crédits requis',

    // ── GPA & Calculator ──────────────────────────────────
    'gpa.trendTitle': 'Tendance de la MPC cumulative',
    'gpa.calculatorSubtitle': 'Calculez ce dont vous avez besoin pour atteindre votre objectif',
    'gpa.currentGpa': 'MPC actuelle',
    'gpa.creditsCompleted': 'Crédits complétés',
    'gpa.creditsRemaining': 'Crédits restants',
    'gpa.targetGpa': 'MPC cible',
    'gpa.requiredGpa': 'MPC requise pour les cours restants',
    'gpa.equivalentGrade': 'Équivalent à maintenir environ :',
    'gpa.notAchievable': 'Objectif non atteignable',
    'gpa.calculateRequired': 'Calculer la MPC requise',
    'gpa.toReach': 'Pour atteindre',
    'gpa.withRemaining': 'MPC avec',
    'gpa.whatIfScenarios': 'Scénarios hypothétiques',
    'gpa.scenarioConservative': 'Conservateur (moyenne B)',
    'gpa.scenarioStrong': 'Fort (moyenne A-)',
    'gpa.scenarioPerfect': 'Parfait (moyenne A)',
    'gpa.finalGpa': 'MPC finale',
    'gpa.tipsToReach': 'Conseils pour atteindre votre objectif',
    'gpa.calculateAnother': 'Calculer un autre objectif',
    'gpa.tryDifferent': 'Essayer un autre objectif',
    'gpa.impossibleMessage': 'Impossible à atteindre. Même avec une MPC parfaite de 4.0 pour tous les cours restants, votre MPC finale ne serait que de',
    'gpa.alreadyExceeded': 'Vous avez déjà dépassé votre objectif ! Votre MPC actuelle de {current} atteindra {target} même si vous obtenez 0.0 dans les cours restants.',
    'gpa.difficultyEasy': 'Facile',
    'gpa.difficultyModerate': 'Modéré',
    'gpa.difficultyChallenging': 'Difficile',
    'gpa.difficultyDifficult': 'Très difficile',
    'gpa.difficultyVeryDifficult': 'Extrêmement difficile',
    'gpa.current': 'Actuelle',
    'gpa.currentGpaLabel': 'MPC actuelle',
    'gpa.semester': 'trimestre',
    'gpa.semesters': 'trimestres',
    'gpa.semesterShort': 'Trim',
    'gpa.addGradesPrompt': 'Ajoutez les notes de trimestre pour voir votre tendance MPC',
    'gpa.courses': 'cours',

    // ── Mark Complete Modal ───────────────────────────────
    'modal.markComplete': 'Marquer le cours comme complété',
    'modal.term': 'Trimestre',
    'modal.year': 'Année',
    'modal.grade': 'Note (facultatif)',
    'modal.notSpecified': 'Non spécifié',
    'modal.fall': 'Automne',
    'modal.winter': 'Hiver',
    'modal.summer': 'Été',

    // ── Achievements & Insights ───────────────────────────
    'achievements.title': 'Réalisations',
    'insights.title': 'Recommandations personnalisées',
    'insights.subtitle': 'Recommandations basées sur votre profil et activité',
    'insights.completeProfile': 'Complétez votre profil et interagissez avec le conseiller IA pour obtenir des recommandations personnalisées !',

    // ── Course Timeline ───────────────────────────────────
    'timeline.noCourses': 'Aucun cours complété. Marquez des cours comme suivis dans l\'onglet Sauvegardés !',

    // ── Forum ─────────────────────────────────────────────
    'forum.comingSoon': 'Bientôt disponible',
    'forum.title': 'Forum communautaire McGill',
    'forum.launchDate': 'Lancement printemps 2026',
    'forum.whatsComingTitle': 'Ce qui s\'en vient',
    'forum.sneakPeek': 'Aperçu',
    'forum.sneakPeekSubtitle': 'Voici à quoi ressemblera le forum',
    'forum.recentDiscussions': 'Discussions récentes',
    'forum.beAmongFirst': 'Soyez parmi les premiers',
    'forum.joinWaitlist': 'Inscrivez-vous à la liste d\'attente pour un accès anticipé et aidez à façonner la communauté',
    'forum.subtitle': 'Connectez-vous avec vos camarades, partagez vos expériences et obtenez des conseils de la communauté McGill',
    'forum.feature1Title': 'Poser des questions',
    'forum.feature1Desc': "Obtenez de l'aide des étudiants McGill sur les cours, les professeurs et les études",
    'forum.feature2Title': 'Connecter avec les camarades',
    'forum.feature2Desc': "Trouvez des groupes d'étude, partagez des notes et collaborez sur des projets",
    'forum.feature3Title': 'Partager des expériences',
    'forum.feature3Desc': 'Évaluez les cours, notez les professeurs et aidez les autres à prendre de bonnes décisions',
    'forum.feature4Title': 'Planification académique',
    'forum.feature4Desc': 'Discutez des exigences de diplôme, des préalables et des parcours académiques',
    'forum.newPost': '+ Nouveau sujet',
    'forum.replies': 'réponses',
    'forum.likes': "j'aime",
    'forum.joinWaitlistBtn': "Rejoindre la liste d'attente",
    'forum.waitlistPlaceholder': 'Entrez votre courriel pour rejoindre la liste',
    'forum.waitlistSuccess': 'Vous êtes sur la liste! Nous vous avertirons au lancement.',
    'forum.comingSoonLabel': 'Bientôt disponible',

    // ── Auth / Login ──────────────────────────────────────
    'auth.aiAdvisor': 'Conseiller académique IA',
    'auth.aiRecommendations': 'Recommandations alimentées par l\'IA',
    'auth.historicalData': 'Données historiques de notes',
    'auth.coursePlanning': 'Planification de cours personnalisée',
    'auth.username': 'Nom d\'utilisateur',
    'auth.email': 'Adresse courriel',
    'auth.password': 'Mot de passe',

    // ── Errors ────────────────────────────────────────────
    'error.authInitFailed': 'Impossible d\'initialiser l\'authentification',
    'error.refreshPage': 'Veuillez rafraîchir la page ou vérifier votre connexion Internet.',
    'error.profileSetupIssue': 'Problème de configuration du profil',
    'error.profileSetupDesc': 'Un problème est survenu lors de la configuration de votre profil. Veuillez vous déconnecter et réessayer.',
    'error.sessionSetup': 'Configuration de votre session...',
    'error.loadingProfile': 'Chargement de votre profil...',

    // ── Sign Out Confirmation ─────────────────────────────
    'signOut.confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'signOut.button': 'Déconnexion',

    // ── Degree Planning ───────────────────────────────────
    'dp.generatingRecs': 'Génération de recommandations personnalisées…',
    'dp.retry': 'Réessayer',
    'dp.loadingRequirements': 'Chargement des exigences…',
    'dp.requirementsNotLoaded': 'Exigences non chargées.',
    'dp.loadRequirements': 'Charger les exigences',
    'dp.loading': 'Chargement…',
    'dp.notAvailable': 'Les exigences détaillées pour {programs} ne sont pas encore disponibles. Nous travaillons à ajouter plus de programmes !',
    'dp.browseDegreeReqs': "Vous pouvez toujours consulter les programmes disponibles dans l'onglet Exigences du diplôme.",
    'dp.notAvailableShort': 'Les exigences détaillées pour {program} ne sont pas encore disponibles.',
    'dp.checkDegreeReqs': "Consultez l'onglet Exigences du diplôme pour parcourir les programmes disponibles.",
    'dp.credits': 'crédits',
    'dp.electives': '✦ Cours au choix',
    'dp.tabCore': 'Tronc commun : {label}',
    'dp.tabConcentration': 'Concentration : {label}',
    'dp.tabScience': 'Sciences : {label}',
    'dp.tabMinor': 'Mineure : {label}',
    'dp.tabMajor': 'Majeure : {label}',
    'dp.ringCore': 'Tronc commun',
    'dp.ringMajor': 'Majeure',
    'dp.ringMinor': 'Mineure',
    'dp.ringConcentration': 'Concentration',
    'dp.foundationWaived': 'Année de fondation dispensée',
    'dp.foundationWaivedDesc': 'Vos {count} crédits de transfert vous exemptent des exigences de fondation U0',
    'dp.foundationWaivedNote': '(note : 30 cr pour exemption complète)',
    'dp.myDegree': 'Mon diplôme',
    'dp.myCourses': 'Mon diplôme',
    'dp.degreeRequirements': 'Exigences du diplôme',
    'dp.studyAbroad': 'Études à l\'étranger',
    'dp.transcript': 'Relevé de notes',
    'dp.syllabuses': 'Plans de cours',
    'dp.na': '(N/D)',
    'dp.statusTransfer': 'Transfert',
    'dp.statusDone': 'Complété',
    'dp.statusTaking': 'En cours',
    'dp.creditsOf': '{earned} / {total} crédits',
    'dp.myProgramRequirements': 'Mes exigences de programme',
    'dp.welcomeTitle': 'Exigences du diplôme',
    'dp.welcomeDesc': 'Sélectionnez un programme dans la barre latérale pour voir ses exigences complètes, votre progression et les cours recommandés.',
    'dp.programsAvailable': '{count} programmes disponibles',
    'dp.programAvailable': '{count} programme disponible',
    'dp.loadBtn': 'Charger les exigences',
    'dp.loadingSpinner': 'Chargement des exigences…',
    'dp.notFoundTitle': 'Programme pas encore disponible',
    'dp.notFoundDesc': "Les exigences détaillées pour ce programme n'ont pas encore été ajoutées. Nous travaillons à élargir notre couverture !",
    'dp.notFoundHint': 'Essayez de sélectionner un autre programme dans la barre latérale, ou revenez plus tard.',
    'dp.loadError': 'Impossible de charger les détails du programme. Veuillez réessayer.',

    // ── Academic Brief ────────────────────────────────────
    'brief.title': 'Bilan académique',
    'brief.updated': 'Mis à jour {time}',
    'brief.refresh': 'Actualiser les fiches',
    'brief.all': 'Tout',
    'brief.saved': 'Sauvegardés',
    'brief.history': 'Historique',
    'brief.preparing': 'Votre bilan académique est en cours de préparation.',
    'brief.generateNow': 'Générer maintenant',
    'brief.noHistory': "Aucun historique de chat. Commencez une conversation sur n'importe quelle fiche.",
    'brief.noSaved': 'Aucune fiche sauvegardée. Marquez des fiches pour les retrouver ici.',
    'brief.noCards': 'Aucune fiche {category} pour le moment.',
    'brief.placeholder': 'Posez une question sur vos études — crée une nouvelle fiche de chat',
    'brief.askedByYou': 'Posé par vous',
    'brief.savedBadge': 'Sauvegardé',
    'brief.pinnedBadge': 'Épinglé',
    'brief.deleteCard': 'Supprimer la fiche',
    'brief.removeBookmark': 'Retirer le signet',
    'brief.bookmark': 'Signet',
    'brief.unpin': 'Désépingler de la barre latérale',
    'brief.pin': 'Épingler dans la barre latérale',
    'brief.dragReorder': 'Glisser pour réorganiser',
    'brief.you': 'Vous',
    'brief.ai': 'IA',
    'brief.msgs': '{n} msg',
    'brief.msgsPlural': '{n} msgs',
    'brief.errorSend': "Une erreur s'est produite. Veuillez réessayer.",
    'brief.followUpPlaceholder': 'Posez une question de suivi…',
    'brief.catDeadlines': 'Échéances',
    'brief.catDegree': 'Diplôme',
    'brief.catCourses': 'Cours',
    'brief.catGrades': 'Notes',
    'brief.catPlanning': 'Planification',
    'brief.catOpportunities': 'Opportunités',
    'brief.catOther': 'Autre',
    'brief.timeJustNow': "à l'instant",
    'brief.time1Min': 'il y a 1 min',
    'brief.timeMins': 'il y a {n} min',
    'brief.timeHours': 'il y a {n}h',

    // ── Calendar missing keys ──────────────────────────────
    'calendar.remindSameDay': 'Même jour',
    'calendar.notifOn': 'ACT.',
    'calendar.notifOff': 'DÉS.',
    'calendar.enableNotifications': 'Activer les rappels pour cet événement',

    // ── Right Sidebar / Website Assistant ─────────────────
    'rsb.pinnedChat': 'Chat épinglé',
    'rsb.unpinCard': 'Désépingler la fiche',
    'rsb.closeSidebar': 'Fermer la barre latérale',
    'rsb.noMessages': "Aucun message pour l'instant. Posez une question de suivi ci-dessous.",
    'rsb.websiteAssistant': 'Assistant du site',
    'rsb.askAnything': 'Posez-moi une question',
    'rsb.close': 'Fermer',
    'rsb.openPinned': 'Ouvrir le chat épinglé',
    'rsb.openAssistant': "Ouvrir l'assistant du site",
    'rsb.navPlaceholder': 'Posez-moi une question sur les cours, la planification ou la navigation…',
    'rsb.errorMsg': '❌ Une erreur est survenue. Veuillez réessayer.',
    'rsb.greeting': "Bonjour ! Je suis votre conseiller académique. Vous êtes sur {tab} — posez-moi n'importe quelle question ou choisissez une suggestion ci-dessous.",
    'rsb.followUpPlaceholder': 'Posez une question de suivi…',

    // Nav suggestion chips per tab (FR)
    'rsb.nav.courses.1': 'Comment rechercher un cours ?',
    'rsb.nav.courses.2': 'Que signifient les badges MPC ?',
    'rsb.nav.courses.3': 'Comment marquer un cours comme complété ?',
    'rsb.nav.calendar.1': 'Comment ajouter un événement ?',
    'rsb.nav.calendar.2': 'Comment téléverser un plan de cours ?',
    'rsb.nav.calendar.3': "Où sont mes dates d'examens finaux ?",
    'rsb.nav.degree.1': 'Comment fonctionne le suivi du diplôme ?',
    'rsb.nav.degree.2': "Qu'est-ce qu'un cours complémentaire ?",
    'rsb.nav.degree.3': 'Comment ajouter une mineure ?',
    'rsb.nav.profile.1': 'Comment téléverser mon relevé de notes ?',
    'rsb.nav.profile.2': 'Comment ajouter des crédits de transfert ?',
    'rsb.nav.profile.3': 'Comment changer ma majeure ?',
    'rsb.nav.abroad.1': 'Comment fonctionnent les échanges à McGill ?',
    'rsb.nav.abroad.2': 'Quels programmes sont en Europe ?',
    'rsb.nav.abroad.3': 'Comment les crédits sont-ils transférés ?',
    'rsb.nav.default.1': 'Comment puis-je vous aider ?',
    'rsb.nav.default.2': 'Comment planifier mon diplôme ?',
    'rsb.nav.default.3': 'Montrez-moi mes options de cours',

    // Tab labels used in greeting (FR)
    'rsb.tab.courses': 'Cours',
    'rsb.tab.calendar': 'Calendrier',
    'rsb.tab.degree': 'Planification académique',
    'rsb.tab.profile': 'Profil',
    'rsb.tab.abroad': "Études à l'étranger",
    'rsb.tab.default': 'le tableau de bord',

    // ── CoursesTab RMP labels ─────────────────────────────
    'courses.yourProf': '📄 Votre prof',
    'courses.rmpLooking': 'Recherche sur RateMyProfessors…',
    'courses.rmpFind': 'Trouver {name} sur RateMyProfessors →',
    'courses.rmpViewLink': 'Voir sur RMP',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem('language')
    return stored === 'fr' ? 'fr' : 'en'
  })

  const setLanguage = useCallback((lang) => {
    const valid = lang === 'fr' ? 'fr' : 'en'
    setLanguageState(valid)
    localStorage.setItem('language', valid)
  }, [])

  const t = useCallback((key) => {
    return translations[language]?.[key] ?? translations.en?.[key] ?? key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
